const PDMSC = Object.freeze({
  VERSION: '1.2.0-document-generation-pipeline-d01',
  BUILD_DATE: '2026-09-09',
  WEB_BUILD: 'D01-PRODUCTION-READINESS-PRE-ISSUE-SAFETY-V0.2.4-20260909',
  TIMEZONE: 'Asia/Bangkok',
  PERIOD_MONTHS: 6,
  PROP_ACTIVE_PERIOD: 'PDMSC_ACTIVE_PERIOD_ID',
  PROP_SCHEMA_VERSION: 'PDMSC_SCHEMA_VERSION',
  PROP_INSTALL_ID: 'PDMSC_INSTALL_ID',
  PROP_LAST_EMP_NO: 'PDMSC_LAST_EMP_NO',
  PROP_PHASE1_MIGRATION_PREVIEW: 'PDMSC_PHASE1_MIGRATION_PREVIEW',
  PROP_RECOVERY_EPOCH: 'PDMSC_RECOVERY_EPOCH',
  PROP_WEB_APP_URL: 'PDMSC_WEB_APP_URL',
  PROP_LEAVE_PREVIEW: 'PDMSC_LEAVE_PREVIEW',
  PROP_PERSONNEL_BULK_PREVIEW: 'PDMSC_PERSONNEL_BULK_PREVIEW',
  SCHEMA_VERSION: '1.8.1',
  BACKEND: Object.freeze({
    CONFIG: '__PDMSC_CFG',
    PERSONNEL: '__PDMSC_PERSONNEL',
    NAME_MAP: '__PDMSC_NAME_MAP',
    EXCLUSIONS: '__PDMSC_EXCLUSIONS',
    OP_RULES: '__PDMSC_OP_RULES',
    MASTER_POSITION: '__PDMSC_MASTER_POSITION',
    MASTER_DEPARTMENT: '__PDMSC_MASTER_DEPARTMENT',
    MASTER_LEAVE_TYPE: '__PDMSC_MASTER_LEAVE_TYPE',
    MASTER_NAME_PREFIX: '__PDMSC_MASTER_NAME_PREFIX',
    PERIODS: '__PDMSC_PERIODS',
    WARNING_RULES: '__PDMSC_WARNING_RULES',
    RAW_LEAVE: '__PDMSC_RAW_LEAVE',
    LEAVE_STORE: '__PDMSC_LEAVE',
    RAW_ATTENDANCE: '__PDMSC_RAW_ATT',
    EVENT_STORE: '__PDMSC_EVENTS',
    DECISIONS: '__PDMSC_DECISIONS',
    DOC_HISTORY: '__PDMSC_DOC_HISTORY',
    MONTHLY_DOC_HISTORY: '__PDMSC_MONTHLY_DOC_HISTORY',
    JOBS: '__PDMSC_JOBS',
    LOG: '__PDMSC_LOG'
  }),
  DECISION: Object.freeze({
    NORMAL: 'NORMAL',
    EXCLUDED: 'EXCLUDED',
    EXCLUDED_KEEP_STATS: 'EXCLUDED_KEEP_STATS',
    PENDING: 'PENDING'
  }),
  PERSONNEL_STATUS: Object.freeze({
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
  }),
  MAP_STATUS: Object.freeze({
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
  }),
  SCOPE_TYPE: Object.freeze({
    EMP_ID: 'EMP_ID',
    SOURCE_NAME: 'SOURCE_NAME'
  }),
  JOB_STATUS: Object.freeze({
    PENDING: 'PENDING', RUNNING: 'RUNNING', PAUSED: 'PAUSED', CANCEL_REQUESTED: 'CANCEL_REQUESTED',
    COMPLETED: 'COMPLETED', ERROR: 'ERROR', CANCELLED: 'CANCELLED'
  })
});
