function onOpen() { pdmscBuildMenu_(); }
function pdmscBuildMenu_() {
  const ui=SpreadsheetApp.getUi();
  ui.createMenu('PDMS')
    .addItem('เปิด PDMS Web App','pdmscOpenWebAppFromSheet')
    .addItem('ตั้งค่า Web App URL','pdmscShowWebAppUrlSetupDialog')
    .addItem('ข้อมูลการ Deploy Web App','pdmscShowWebAppDeploymentInfo')
    .addSeparator()
    .addItem('ศูนย์ควบคุมแบบเดิม (สำรอง)','pdmscOpenControlCenter')
    .addSeparator()
    .addSubMenu(ui.createMenu('การลา')
      .addItem('นำเข้าข้อมูลลาทั้งรอบ','pdmscMenuNotBuiltYet_')
      .addItem('ตรวจรายการใหม่ / รายการที่เปลี่ยน','pdmscMenuNotBuiltYet_'))
    .addSubMenu(ui.createMenu('ลงเวลา')
      .addItem('นำเข้าข้อมูลลงเวลาทั้งเดือน','pdmscMenuNotBuiltYet_')
      .addItem('ประมวลผลเดือน','pdmscMenuNotBuiltYet_')
      .addItem('ดูผลต่างจากรอบก่อน','pdmscMenuNotBuiltYet_'))
    .addSubMenu(ui.createMenu('ตรวจรายการ')
      .addItem('รายการที่ต้องตรวจ','pdmscMenuNotBuiltYet_')
      .addItem('ตรวจรายละเอียดการสแกน','pdmscMenuNotBuiltYet_')
      .addItem('รายการที่ยกเว้นแล้ว','pdmscMenuNotBuiltYet_'))
    .addSubMenu(ui.createMenu('สรุปสถิติ')
      .addItem('ดูสรุปรายบุคคล / รายเดือน / ทั้งรอบ','pdmscMenuNotBuiltYet_'))
    .addSubMenu(ui.createMenu('หนังสือ')
      .addItem('ตรวจผู้เข้าเกณฑ์หนังสือเตือน','pdmscMenuNotBuiltYet_')
      .addItem('ออกหนังสือเตือน','pdmscMenuNotBuiltYet_')
      .addItem('สร้างหนังสือสรุปรายเดือน','pdmscMenuNotBuiltYet_')
      .addItem('ประวัติหนังสือ','pdmscMenuNotBuiltYet_'))
    .addSubMenu(ui.createMenu('ตั้งค่า')
      .addItem('บุคลากรและการจับคู่','pdmscOpenPersonnelCenter')
      .addItem('วันทำงาน / วันหยุด / วันพิเศษ','pdmscMenuNotBuiltYet_')
      .addItem('เวลามาตรฐาน / กฎลงเวลา','pdmscMenuNotBuiltYet_')
      .addItem('กฎหนังสือ / Template / ผู้ลงนาม','pdmscMenuNotBuiltYet_'))
    .addSubMenu(ui.createMenu('ระบบ')
      .addItem('ตรวจสุขภาพระบบ','pdmscShowHealthCheck')
      .addItem('งานที่กำลังประมวลผล','pdmscShowOpenJobs_')
      .addItem('กู้คืนงานค้าง','pdmscShowRecoveryDialog')
      .addSeparator()
      .addItem('เริ่มรอบใหม่','pdmscStartNewPeriod')
      .addItem('Factory Reset ทั้งระบบ','pdmscFactoryReset'))
    .addToUi();
}
function pdmscMenuNotBuiltYet_(){SpreadsheetApp.getUi().alert('โมดูลนี้อยู่ใน Blueprint ที่อนุมัติแล้ว และจะเชื่อมใน Build ถัดไป');}
function pdmscShowOpenJobs_(){const j=pdmscGetOpenJobs();SpreadsheetApp.getUi().alert('งานที่กำลังประมวลผล',j.length?j.map(x=>x.jobId+' | '+x.jobType+' | '+x.monthKey+' | '+x.status+' | '+x.stage).join('\n'):'ไม่มีงานค้าง',SpreadsheetApp.getUi().ButtonSet.OK);}
