function pdmscNormalizeText_(v){return String(v==null?'':v).replace(/\u00a0/g,' ').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/\s+/g,' ').trim();}
function pdmscNormalizeName_(v){return pdmscNormalizeText_(v).toLowerCase().replace(/\s+/g,' ');}
function pdmscCompactName_(v){return pdmscNormalizeName_(v).replace(/[.\-_/\\()[\]{}'"“”‘’:;,]/g,'').replace(/\s+/g,'').trim();}
function pdmscBool_(v){if(v===true)return true;const s=pdmscNormalizeText_(v).toUpperCase();return ['TRUE','1','YES','Y','ACTIVE','ใช้งาน'].indexOf(s)>=0;}
function pdmscUiScalar_(v){if(v instanceof Date)return Utilities.formatDate(v,PDMSC.TIMEZONE,"yyyy-MM-dd'T'HH:mm:ss");return v==null?'':v;}
function pdmscPersonnelDate_(value){
  if(value instanceof Date&&!isNaN(value.getTime()))return new Date(value.getFullYear(),value.getMonth(),value.getDate());
  const s=pdmscNormalizeText_(value);if(!s)return null;
  let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m){let y=Number(m[1]);if(y>2400)y-=543;const d=new Date(y,Number(m[2])-1,Number(m[3]));return d.getFullYear()===y&&d.getMonth()===Number(m[2])-1&&d.getDate()===Number(m[3])?d:null;}
  m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m){let y=Number(m[3]);if(y>2400)y-=543;const d=new Date(y,Number(m[2])-1,Number(m[1]));return d.getFullYear()===y&&d.getMonth()===Number(m[2])-1&&d.getDate()===Number(m[1])?d:null;}
  return null;
}
function pdmscPersonnelDateIso_(value){const d=pdmscPersonnelDate_(value);return d?Utilities.formatDate(d,PDMSC.TIMEZONE,'yyyy-MM-dd'):'';}
function pdmscPersonnelDateUi_(value){const d=pdmscPersonnelDate_(value);return d?Utilities.formatDate(d,PDMSC.TIMEZONE,'dd/MM/')+(d.getFullYear()+543):'';}
function pdmscPersonnelRows_(){return pdmscRows_(PDMSC.BACKEND.PERSONNEL).map((r,i)=>({row:i+2,empId:pdmscNormalizeText_(r[0]),fullName:pdmscNormalizeText_(r[1]),position:pdmscNormalizeText_(r[2]),department:pdmscNormalizeText_(r[3]),active:pdmscBool_(r[4]),matchName:pdmscNormalizeName_(r[5]||r[1]),createdAt:r[6]||'',updatedAt:r[7]||'',note:pdmscNormalizeText_(r[8]),employmentStartDate:pdmscPersonnelDate_(r[9]),employmentEndDate:pdmscPersonnelDate_(r[10])})).filter(x=>x.empId||x.fullName);}
function pdmscNextEmpId_(){const rows=pdmscPersonnelRows_();let max=0;rows.forEach(x=>{const m=x.empId.match(/^EMP(\d+)$/i);if(m)max=Math.max(max,Number(m[1]));});const props=PropertiesService.getDocumentProperties(),stored=Number(props.getProperty(PDMSC.PROP_LAST_EMP_NO)||0),next=Math.max(max,stored)+1;props.setProperty(PDMSC.PROP_LAST_EMP_NO,String(next));return 'EMP'+String(next).padStart(4,'0');}
function pdmscGetPersonnelList(query,includeInactive){const q=pdmscNormalizeName_(query);return pdmscPersonnelRows_().filter(x=>(includeInactive||x.active)&&(!q||pdmscNormalizeName_(x.empId+' '+x.fullName+' '+x.position+' '+x.department).indexOf(q)>=0)).map(x=>({empId:x.empId,fullName:x.fullName,position:x.position,department:x.department,active:x.active,note:x.note,employmentStartDate:pdmscPersonnelDateIso_(x.employmentStartDate),employmentEndDate:pdmscPersonnelDateIso_(x.employmentEndDate),employmentStartDateUi:pdmscPersonnelDateUi_(x.employmentStartDate),employmentEndDateUi:pdmscPersonnelDateUi_(x.employmentEndDate)}));}
function pdmscGetPersonnel(empId){const id=pdmscNormalizeText_(empId).toUpperCase(),p=pdmscPersonnelRows_().find(x=>x.empId.toUpperCase()===id);if(!p)throw new Error('ไม่พบบุคลากร '+id);return p;}
function pdmscWritePersonnelUnlocked_(payload,mode){payload=payload||{};mode=pdmscNormalizeText_(mode||payload.mode||'').toUpperCase();if(['CREATE','EDIT'].indexOf(mode)<0)throw new Error('ไม่พบโหมดบันทึกบุคลากร กรุณาปิดหน้าต่างแล้วเปิดใหม่');const rows=pdmscPersonnelRows_(),now=new Date();let empId=pdmscNormalizeText_(payload.empId).toUpperCase();const originalEmpId=pdmscNormalizeText_(payload.originalEmpId).toUpperCase(),fullName=pdmscNormalizeText_(payload.fullName);if(!fullName)throw new Error('กรุณากรอกชื่อ-นามสกุล');if(empId&&!/^EMP\d+$/i.test(empId))throw new Error('EMP ID ต้องอยู่ในรูป EMP0001');let target=null;if(mode==='CREATE'){if(empId&&rows.some(x=>x.empId.toUpperCase()===empId))throw new Error('สร้างบุคลากรใหม่ไม่ได้: EMP ID '+empId+' มีอยู่แล้ว');if(!empId)empId=pdmscNextEmpId_();}else{if(!originalEmpId)throw new Error('ไม่พบ EMP ID เดิมของรายการที่กำลังแก้ไข');if(empId&&empId!==originalEmpId)throw new Error('EMP ID เป็นรหัสหลักและเปลี่ยนไม่ได้ในโหมดแก้ไข');empId=originalEmpId;target=rows.find(x=>x.empId.toUpperCase()===empId);if(!target)throw new Error('ไม่พบบุคลากรเดิม '+empId+' กรุณาโหลดข้อมูลใหม่');}const normalized=pdmscNormalizeName_(fullName),sameName=rows.find(x=>x.matchName===normalized&&x.empId.toUpperCase()!==empId);if(sameName)throw new Error('ชื่อหลักซ้ำกับ '+sameName.empId+' '+sameName.fullName);const position=pdmscMasterValidateActiveName_('POSITION',payload.position,'ตำแหน่ง'),department=pdmscMasterValidateActiveName_('DEPARTMENT',payload.department,'กลุ่ม/ฝ่าย');
const startRaw=pdmscNormalizeText_(payload.employmentStartDate),endRaw=pdmscNormalizeText_(payload.employmentEndDate),employmentStartDate=startRaw?pdmscPersonnelDate_(startRaw):null,employmentEndDate=endRaw?pdmscPersonnelDate_(endRaw):null;
if(startRaw&&!employmentStartDate)throw new Error('วันที่เริ่มงานไม่ถูกต้อง');if(endRaw&&!employmentEndDate)throw new Error('วันที่สิ้นสุดงานไม่ถูกต้อง');if(employmentStartDate&&employmentEndDate&&employmentEndDate<employmentStartDate)throw new Error('วันที่สิ้นสุดงานต้องไม่ก่อนวันที่เริ่มงาน');
const sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.PERSONNEL),values=[empId,fullName,position,department,payload.active===false?false:true,normalized,target?target.createdAt:now,now,pdmscNormalizeText_(payload.note),employmentStartDate||'',employmentEndDate||''];if(target)sh.getRange(target.row,1,1,values.length).setValues([values]);else sh.appendRow(values);pdmscWebCacheClear_(['personnel','dashboard']);pdmscLog_('PERSONNEL_SAVE','OK',{empId:empId,mode:mode,fullName:fullName,employmentStartDate:pdmscPersonnelDateIso_(employmentStartDate),employmentEndDate:pdmscPersonnelDateIso_(employmentEndDate)});return{empId:empId,fullName:fullName,position:values[2],department:values[3],active:values[4],note:values[8],employmentStartDate:pdmscPersonnelDateIso_(employmentStartDate),employmentEndDate:pdmscPersonnelDateIso_(employmentEndDate),employmentStartDateUi:pdmscPersonnelDateUi_(employmentStartDate),employmentEndDateUi:pdmscPersonnelDateUi_(employmentEndDate)};}
function pdmscSavePersonnel(payload){const lock=LockService.getDocumentLock();lock.waitLock(30000);try{return pdmscWritePersonnelUnlocked_(payload,payload&&payload.mode);}finally{lock.releaseLock();}}
function pdmscSetPersonnelActive(empId,active){const lock=LockService.getDocumentLock();lock.waitLock(30000);try{const p=pdmscGetPersonnel(empId),sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.PERSONNEL);sh.getRange(p.row,5).setValue(!!active);sh.getRange(p.row,8).setValue(new Date());pdmscWebCacheClear_(['personnel','dashboard']);pdmscLog_('PERSONNEL_ACTIVE','OK',{empId:p.empId,active:!!active});return{empId:p.empId,active:!!active};}finally{lock.releaseLock();}}
function pdmscDeletePersonnelIfUnused(empId){const id=pdmscNormalizeText_(empId).toUpperCase(),deps=[PDMSC.BACKEND.NAME_MAP,PDMSC.BACKEND.EXCLUSIONS,PDMSC.BACKEND.LEAVE_STORE,PDMSC.BACKEND.RAW_ATTENDANCE,PDMSC.BACKEND.EVENT_STORE,PDMSC.BACKEND.DECISIONS,PDMSC.BACKEND.DOC_HISTORY],hits=[];deps.forEach(name=>{const sh=SpreadsheetApp.getActive().getSheetByName(name);if(!sh||sh.getLastRow()<2)return;const vals=sh.getDataRange().getDisplayValues();let count=0;vals.slice(1).forEach(r=>{if(r.some(v=>pdmscNormalizeText_(v).toUpperCase()===id))count++;});if(count)hits.push(name+': '+count);});if(hits.length)throw new Error('ลบบุคลากรถาวรไม่ได้ เพราะมีข้อมูลอ้างอิง\n'+hits.join('\n')+'\nให้ใช้ “ปิดใช้งาน” แทน');const p=pdmscGetPersonnel(id);SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.PERSONNEL).deleteRow(p.row);pdmscLog_('PERSONNEL_DELETE','OK',{empId:id});return{ok:true,empId:id};}
