function pdmscWebPersonnelList(query,includeInactive){const rows=pdmscGetPersonnelList(query||'',includeInactive!==false);return rows.map(x=>({empId:x.empId,fullName:x.fullName,position:x.position,department:x.department,active:!!x.active,note:x.note||'',employmentStartDate:x.employmentStartDate||'',employmentEndDate:x.employmentEndDate||'',employmentStartDateUi:x.employmentStartDateUi||'',employmentEndDateUi:x.employmentEndDateUi||''}));}
function pdmscWebPersonnelSummary(){const qa=pdmscPersonnelQaReport_();return{ok:qa.ok,counts:qa.counts,issues:(qa.issues||[]).slice(0,50)};}
function pdmscWebPersonnelBootstrap(force){const key='personnel-bootstrap';if(!force){const cached=pdmscWebCacheGet_(key);if(cached)return cached;}let masters=pdmscWebCacheGet_('personnel-masters');if(!masters){masters={positions:pdmscMasterList_('POSITION',true),departments:pdmscMasterList_('DEPARTMENT',true)};pdmscWebCachePut_('personnel-masters',masters,60);}const out={personnel:pdmscWebPersonnelList('',true),masters};pdmscWebCachePut_(key,out,60);return out;}
function pdmscWebPersonnelSave(payload){payload=payload||{};const mode=String(payload.mode||'').toUpperCase();if(['CREATE','EDIT'].indexOf(mode)<0)throw new Error('โหมดบันทึกบุคลากรไม่ถูกต้อง');const saved=pdmscSavePersonnel({mode,originalEmpId:payload.originalEmpId||'',empId:payload.empId||'',fullName:payload.fullName||'',position:payload.position||'',department:payload.department||'',note:payload.note||'',active:payload.active!==false,employmentStartDate:payload.employmentStartDate||'',employmentEndDate:payload.employmentEndDate||''});pdmscWebInvalidatePersonnelCaches_();return{ok:true,person:saved,personnel:pdmscWebPersonnelList('',true)};}
function pdmscWebPersonnelSetActive(empId,active){const r=pdmscSetPersonnelActive(empId,!!active);pdmscWebInvalidatePersonnelCaches_();return{ok:true,result:r};}
function pdmscWebAliasList(empId,force){const id=pdmscNormalizeText_(empId);const key='alias-list-all';if(!id&&!force){const c=pdmscWebCacheGet_(key);if(c)return c;}const people=pdmscWebPersonnelDirectoryMap_(),out=pdmscListAliases(id||'').map(x=>Object.assign({},x,{department:(people[x.empId]||{}).department||'',position:(people[x.empId]||{}).position||''}));if(!id)pdmscWebCachePut_(key,out,180);return out;}
function pdmscWebAliasSave(payload){const r=pdmscSaveAlias({sourceName:(payload||{}).sourceName||'',empId:(payload||{}).empId||'',note:(payload||{}).note||'',sourceType:'WEB'});pdmscWebInvalidateAliasCaches_();return{ok:true,result:r,aliases:pdmscWebAliasList('',true)};}
function pdmscWebAliasSetActive(sourceName,empId,active){const r=pdmscSetAliasActive(sourceName,empId,!!active);pdmscWebInvalidateAliasCaches_();return{ok:true,result:r,aliases:pdmscWebAliasList('',true)};}
function pdmscWebScopeList(force){const key='scope-list-all';if(!force){const c=pdmscWebCacheGet_(key);if(c)return c;}const people=pdmscWebPersonnelDirectoryMap_(),out=pdmscListScopeExclusions().map(x=>Object.assign({},x,{department:x.empId?(people[x.empId]||{}).department||'':''}));pdmscWebCachePut_(key,out,180);return out;}
function pdmscWebScopeSave(payload){const r=pdmscSaveScopeExclusion({scopeType:(payload||{}).scopeType||'',empId:(payload||{}).empId||'',sourceName:(payload||{}).sourceName||'',reason:(payload||{}).reason||'',note:(payload||{}).note||''});pdmscWebInvalidateScopeCaches_();return{ok:true,result:r,scopes:pdmscWebScopeList(true)};}
function pdmscWebScopeSetActive(rowNumber,active){const r=pdmscSetScopeExclusionActive(rowNumber,!!active);pdmscWebInvalidateScopeCaches_();return{ok:true,result:r,scopes:pdmscWebScopeList(true)};}
function pdmscWebPersonnelQa(force){const key='personnel-qa';if(!force){const c=pdmscWebCacheGet_(key);if(c)return c;}const q=pdmscPersonnelQaReport_(),out={ok:q.ok,counts:q.counts,issues:(q.issues||[]).slice(0,100)};pdmscWebCachePut_(key,out,60);return out;}
function pdmscWebPersonnelBulkPreview(text){return pdmscPersonnelBulkPreview_(text);}
function pdmscWebPersonnelBulkCommit(importId,fingerprint){const r=pdmscPersonnelBulkCommit_(importId,fingerprint);pdmscWebInvalidatePersonnelCaches_();return{ok:true,result:r,personnel:pdmscWebPersonnelList('',true)};}
