function pdmscS01Date_(v){if(v instanceof Date&&!isNaN(v))return new Date(v.getFullYear(),v.getMonth(),v.getDate());const s=pdmscNormalizeText_(v),m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return null;const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]));return isNaN(d)?null:d;}
function pdmscS01DateUi_(d){return d instanceof Date?Utilities.formatDate(d,PDMSC.TIMEZONE,'yyyy-MM-dd'):pdmscNormalizeText_(d);}
function pdmscOperationalScopeValues_(value){const a=Array.isArray(value)?value:String(value||'').split(/[|,;\n]+/);const seen=new Set(),out=[];a.forEach(v=>{const x=pdmscNormalizeText_(v);if(x&&!seen.has(x)){seen.add(x);out.push(x);}});return out;}
function pdmscOperationalScopeStore_(values){return pdmscOperationalScopeValues_(values).join(' | ');}
function pdmscOperationalScopeLabel_(scopeType){const s=pdmscNormalizeText_(scopeType).toUpperCase();return s==='GROUP'?'เฉพาะกลุ่ม':s==='EXCEPT_GROUPS'?'ทุกกลุ่มยกเว้น':'ทุกคน';}
function pdmscOperationalRules_(){const sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.OP_RULES);if(!sh||sh.getLastRow()<2)return[];const range=sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()),raw=range.getValues(),display=range.getDisplayValues();return raw.map((r,i)=>{const scopeType=pdmscNormalizeText_(r[3]).toUpperCase()||'ALL',scopeValue=pdmscNormalizeText_(r[4]);return{row:i+2,ruleId:pdmscNormalizeText_(r[0]),startDate:r[1],endDate:r[2],scopeType,scopeValue,scopeValues:pdmscOperationalScopeValues_(scopeValue),action:pdmscNormalizeText_(r[5]).toUpperCase(),cutoff:pdmscTimeHHmm_(r[6],(display[i]||[])[6]||''),eventExemption:pdmscNormalizeText_(r[7])||'NONE',note:pdmscNormalizeText_(r[8]),active:pdmscBool_(r[9]),updatedAt:r[10]||'',outScanPolicy:pdmscNormalizeText_(r[11])||''};}).filter(x=>x.ruleId);}
function pdmscOperationalActionContract_(action){
  const a=pdmscNormalizeText_(action).toUpperCase();
  if(a==='LEAVE_ONLY')return{action:'LEAVE_ONLY',processLeave:true,processAttendanceScan:false,allowLate:false,allowMissingScan:false,description:'ประมวลผลเฉพาะการลา ไม่ตรวจการสแกน'};
  if(a==='IGNORE')return{action:'IGNORE',processLeave:false,processAttendanceScan:false,allowLate:false,allowMissingScan:false,description:'ไม่นำช่วงนี้มาประมวลผล'};
  return{action:'PROCESS',processLeave:true,processAttendanceScan:true,allowLate:true,allowMissingScan:true,description:'ประมวลผลตามปกติ'};
}
function pdmscOperationalActionIsValid_(action){return['PROCESS','IGNORE','LEAVE_ONLY'].includes(pdmscNormalizeText_(action).toUpperCase());}
function pdmscOperationalScopeMatches_(rule,department){const s=pdmscNormalizeText_(rule.scopeType||'ALL').toUpperCase(),dep=pdmscNormalizeText_(department),vals=pdmscOperationalScopeValues_(rule.scopeValues&&rule.scopeValues.length?rule.scopeValues:rule.scopeValue);if(s==='ALL')return true;if(s==='GROUP')return vals.includes(dep);if(s==='EXCEPT_GROUPS')return !vals.includes(dep);return false;}
function pdmscOperationalScopeRank_(rule){const s=pdmscNormalizeText_(rule.scopeType||'ALL').toUpperCase();return s==='GROUP'?3:s==='EXCEPT_GROUPS'?2:1;}
function pdmscOperationalDateOnly_(value){return pdmscS01Date_(value);}
function pdmscOperationalDateInRule_(date,rule){const d=pdmscOperationalDateOnly_(date),start=pdmscOperationalDateOnly_(rule&&rule.startDate),end=pdmscOperationalDateOnly_(rule&&rule.endDate);return !!(d&&start&&end&&d.getTime()>=start.getTime()&&d.getTime()<=end.getTime());}
function pdmscOperationalPriority_(rule){
  const start=pdmscS01Date_(rule.startDate),end=pdmscS01Date_(rule.endDate),span=(start&&end)?(end-start):Number.MAX_SAFE_INTEGER,rank=pdmscOperationalScopeRank_(rule),count=pdmscOperationalScopeValues_(rule.scopeValues&&rule.scopeValues.length?rule.scopeValues:rule.scopeValue).length||999;
  return{span,rank,count,row:Number(rule.row||0)};
}
function pdmscOperationalCompare_(a,b){const pa=pdmscOperationalPriority_(a),pb=pdmscOperationalPriority_(b);if(pa.span!==pb.span)return pa.span-pb.span;if(pa.rank!==pb.rank)return pb.rank-pa.rank;if(pa.count!==pb.count)return pa.count-pb.count;return pb.row-pa.row;}
function pdmscOperationalSamePriority_(a,b){const pa=pdmscOperationalPriority_(a),pb=pdmscOperationalPriority_(b);return pa.span===pb.span&&pa.rank===pb.rank&&pa.count===pb.count;}
function pdmscOperationalField_(active,field,baseValue,accept){
  const rows=(active||[]).filter(r=>accept?accept(r[field],r):pdmscNormalizeText_(r[field])!=='').slice().sort(pdmscOperationalCompare_);if(!rows.length)return{value:baseValue,ruleId:'DEFAULT',peerRuleIds:[],conflict:false};
  const top=rows[0],peers=rows.filter(r=>pdmscOperationalSamePriority_(r,top)),vals=new Set(peers.map(r=>pdmscNormalizeText_(r[field]).toUpperCase()));
  return{value:top[field],ruleId:top.ruleId||'DEFAULT',peerRuleIds:peers.map(r=>r.ruleId),conflict:vals.size>1};
}
function pdmscOperationalResolveFor_(date,department,rules,settings){
  const dep=pdmscNormalizeText_(department),baseCutoff=pdmscTimeHHmm_((settings||{}).LATE_CUTOFF,'')||'07:51',active=(rules||[]).filter(r=>r.active&&pdmscOperationalDateInRule_(date,r)&&pdmscOperationalScopeMatches_(r,dep)).slice().sort(pdmscOperationalCompare_);
  if(!active.length)return{ruleId:'DEFAULT',action:'PROCESS',cutoff:baseCutoff,cutoffRuleId:'DEFAULT',eventExemption:'NONE',scopeType:'ALL',scopeValue:'',scopeValues:[],note:'ใช้ค่าพื้นฐาน',outScanPolicy:'',conflict:false,conflictFields:[],matchedRuleIds:[],resolutionNote:'ไม่มีกฎเฉพาะ ใช้ค่าพื้นฐาน'};
  const top=active[0],topPeers=active.filter(r=>pdmscOperationalSamePriority_(r,top)),actionVals=new Set(topPeers.map(r=>pdmscNormalizeText_(r.action||'PROCESS').toUpperCase())),action=top.action||'PROCESS';
  const cutoffRes=pdmscOperationalField_(active,'cutoff',baseCutoff,v=>!!pdmscTimeHHmm_(v,''));
  const eventRes=pdmscOperationalField_(active,'eventExemption','NONE',v=>pdmscNormalizeText_(v)!=='');
  const outRes=pdmscOperationalField_(active,'outScanPolicy','',v=>pdmscNormalizeText_(v)!=='');
  const conflicts=[];if(actionVals.size>1)conflicts.push('ACTION');if(cutoffRes.conflict)conflicts.push('CUTOFF');if(eventRes.conflict)conflicts.push('EVENT_EXEMPTION');if(outRes.conflict)conflicts.push('OUT_SCAN_POLICY');
  const effectiveCutoff=action==='PROCESS'?(pdmscTimeHHmm_(cutoffRes.value,'')||baseCutoff):'';
  const noteBits=['กฎหลัก '+(top.ruleId||'DEFAULT')];if(action==='PROCESS')noteBits.push('เวลาเริ่มนับสาย '+effectiveCutoff+' จาก '+cutoffRes.ruleId);if(active.length>1)noteBits.push('พบกฎที่ตรง '+active.length+' รายการ');
  return{ruleId:top.ruleId,action,cutoff:effectiveCutoff,cutoffRuleId:cutoffRes.ruleId,eventExemption:eventRes.value||'NONE',eventExemptionRuleId:eventRes.ruleId,scopeType:top.scopeType,scopeValue:top.scopeValue||'',scopeValues:pdmscOperationalScopeValues_(top.scopeValue),note:top.note||'',outScanPolicy:outRes.value||'',outScanPolicyRuleId:outRes.ruleId,conflict:conflicts.length>0,conflictFields:conflicts,peerRuleIds:topPeers.map(x=>x.ruleId),matchedRuleIds:active.map(x=>x.ruleId),resolutionNote:noteBits.join(' | ')};
}
function pdmscOperationalRuleFor_(date,department,rules,settings){return pdmscOperationalResolveFor_(date,department,rules,settings);}
function pdmscOperationalResolverV03SelfTest_(){
  const settings={LATE_CUTOFF:'07:51'},d3=new Date(2026,3,3),d7=new Date(2026,3,7),aug12=new Date(2026,7,12),rules=[
    {row:1,ruleId:'TERM',startDate:new Date(2026,4,11),endDate:new Date(2026,8,30),scopeType:'ALL',scopeValue:'',action:'PROCESS',cutoff:'',eventExemption:'NONE',active:true},
    {row:2,ruleId:'APR1_3',startDate:new Date(2026,3,1),endDate:new Date(2026,3,3),scopeType:'ALL',scopeValue:'',action:'PROCESS',cutoff:'08:31',eventExemption:'NONE',active:true},
    {row:3,ruleId:'BREAK',startDate:new Date(2026,3,4),endDate:new Date(2026,4,10),scopeType:'EXCEPT_GROUPS',scopeValue:'ลูกจ้าง',action:'LEAVE_ONLY',cutoff:'',eventExemption:'NONE',active:true},
    {row:4,ruleId:'MEETING',startDate:d7,endDate:d7,scopeType:'EXCEPT_GROUPS',scopeValue:'ลูกจ้าง',action:'PROCESS',cutoff:'08:31',eventExemption:'NONE',active:true},
    {row:5,ruleId:'AUG12',startDate:aug12,endDate:aug12,scopeType:'ALL',scopeValue:'',action:'IGNORE',cutoff:'',eventExemption:'NONE',active:true}
  ];
  const d3Noon=new Date(2026,3,3,12,0,0),a=pdmscOperationalResolveFor_(d3,'วิทย์ฯ',rules,settings),aNoon=pdmscOperationalResolveFor_(d3Noon,'ฝ่ายบริหาร',rules,settings),b=pdmscOperationalResolveFor_(d7,'วิทย์ฯ',rules,settings),c=pdmscOperationalResolveFor_(aug12,'วิทย์ฯ',rules,settings),e=pdmscOperationalResolveFor_(new Date(2026,3,8,12,0,0),'ลูกจ้าง',rules,settings);
  const tests=[
    {name:'1-3 Apr special cutoff 08:31 wins base 07:51',ok:a.action==='PROCESS'&&a.cutoff==='08:31'&&a.cutoffRuleId==='APR1_3'},
    {name:'end date remains inclusive when Raw Snapshot date is noon',ok:aNoon.action==='PROCESS'&&aNoon.ruleId==='APR1_3'&&aNoon.cutoff==='08:31'},
    {name:'single-day meeting overrides broad school break',ok:b.action==='PROCESS'&&b.ruleId==='MEETING'&&b.cutoff==='08:31'},
    {name:'single-day holiday overrides broad term',ok:c.action==='IGNORE'&&c.ruleId==='AUG12'},
    {name:'except-groups does not apply to excluded group',ok:e.action==='PROCESS'},
    {name:'resolver exposes winning rule evidence',ok:Array.isArray(b.matchedRuleIds)&&b.matchedRuleIds.includes('BREAK')&&b.matchedRuleIds.includes('MEETING')&&!!b.resolutionNote}
  ];return{ok:tests.every(t=>t.ok),tests};
}
function pdmscOperationalNormalizePayload_(payload){payload=payload||{};const start=pdmscS01Date_(payload.startDate),end=pdmscS01Date_(payload.endDate);if(!start||!end||end<start)throw new Error('ช่วงวันที่ในปฏิทินปฏิบัติงานไม่ถูกต้อง');const action=pdmscNormalizeText_(payload.action).toUpperCase();if(!pdmscOperationalActionIsValid_(action))throw new Error('โหมดวันทำงานไม่ถูกต้อง');const scopeType=pdmscNormalizeText_(payload.scopeType||'ALL').toUpperCase();if(!['ALL','GROUP','EXCEPT_GROUPS'].includes(scopeType))throw new Error('ขอบเขตบุคลากรรองรับ ทุกคน / เฉพาะกลุ่ม / ทุกกลุ่มยกเว้น');let scopeValues=[];if(scopeType!=='ALL'){scopeValues=pdmscOperationalScopeValues_(payload.scopeValues&&payload.scopeValues.length?payload.scopeValues:payload.scopeValue);if(!scopeValues.length)throw new Error('กรุณาเลือกกลุ่ม/ฝ่ายอย่างน้อย 1 กลุ่ม');scopeValues=scopeValues.map(x=>pdmscMasterValidateActiveName_('DEPARTMENT',x,'กลุ่ม/ฝ่าย'));}let cutoff=pdmscNormalizeText_(payload.cutoff)?pdmscSettingsValidateTime_(payload.cutoff,'เวลาตัดสายเฉพาะช่วง'):'';if(action==='LEAVE_ONLY')cutoff='';return{ruleId:pdmscNormalizeText_(payload.ruleId),startDate:start,endDate:end,scopeType,scopeValues,scopeValue:scopeType==='ALL'?'':pdmscOperationalScopeStore_(scopeValues),action,cutoff,eventExemption:action==='LEAVE_ONLY'?'NONE':pdmscNormalizeText_(payload.eventExemption||'NONE').toUpperCase(),note:pdmscNormalizeText_(payload.note),active:payload.active===false?false:true,outScanPolicy:action==='LEAVE_ONLY'?'':pdmscNormalizeText_(payload.outScanPolicy)};}
function pdmscOperationalRuleSig_(r){if(!r)return'';return[r.ruleId||'',r.action||'',r.cutoff||'',r.eventExemption||'',r.scopeType||'',r.scopeValue||'',r.outScanPolicy||''].join('|');}
function pdmscOperationalImpactPreview_(payload){const proposed=pdmscOperationalNormalizePayload_(payload),current=pdmscOperationalRules_(),old=proposed.ruleId?current.find(x=>x.ruleId===proposed.ruleId):null,sim=Object.assign({},proposed,{row:old?old.row:999999,ruleId:proposed.ruleId||'PREVIEW_RULE'}),next=current.filter(x=>x.ruleId!==proposed.ruleId).concat([sim]),resolver=pdmscBuildBulkResolverContext_(),people=new Map(resolver.people.map(p=>[pdmscNormalizeText_(p.empId).toUpperCase(),p])),settings=pdmscSettingsMap_(),raw=pdmscRows_(PDMSC.BACKEND.RAW_ATTENDANCE),changed=[],groups=new Set();raw.forEach(r=>{const d=r[4] instanceof Date?r[4]:pdmscS01Date_(r[4]);if(!d)return;const inOld=old&&pdmscOperationalDateInRule_(d,old),inNew=pdmscOperationalDateInRule_(d,proposed);if(!inOld&&!inNew)return;const emp=pdmscNormalizeText_(r[2]).toUpperCase(),person=people.get(emp)||{},dep=pdmscNormalizeText_(person.department),before=pdmscOperationalRuleFor_(d,dep,current,settings),after=pdmscOperationalRuleFor_(d,dep,next,settings);if(pdmscOperationalRuleSig_(before)!==pdmscOperationalRuleSig_(after)){const key=emp+'|'+Utilities.formatDate(d,PDMSC.TIMEZONE,'yyyyMMdd');changed.push(key);if(dep)groups.add(dep);}});const changedSet=new Set(changed),esh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.EVENT_STORE);let activeEvents=0;if(esh&&esh.getLastRow()>1)esh.getRange(2,1,esh.getLastRow()-1,esh.getLastColumn()).getValues().forEach(r=>{if(pdmscNormalizeText_(r[10]).toUpperCase()!=='ACTIVE')return;const d=r[3] instanceof Date?r[3]:pdmscS01Date_(r[3]);if(!d)return;const key=pdmscNormalizeText_(r[2]).toUpperCase()+'|'+Utilities.formatDate(d,PDMSC.TIMEZONE,'yyyyMMdd');if(changedSet.has(key))activeEvents++;});return{ok:true,editing:!!old,ruleId:proposed.ruleId||'',before:old?{startDate:pdmscS01DateUi_(old.startDate),endDate:pdmscS01DateUi_(old.endDate),scopeType:old.scopeType,scopeValues:pdmscOperationalScopeValues_(old.scopeValue),action:old.action,cutoff:old.cutoff||'',note:old.note||''}:null,after:{startDate:pdmscS01DateUi_(proposed.startDate),endDate:pdmscS01DateUi_(proposed.endDate),scopeType:proposed.scopeType,scopeValues:proposed.scopeValues,action:proposed.action,cutoff:proposed.cutoff||'',note:proposed.note||''},changedPersonDays:changedSet.size,activeFinalEvents:activeEvents,departments:[...groups].sort((a,b)=>a.localeCompare(b,'th')),needsReprocess:activeEvents>0};}
function pdmscOperationalSave_(payload){const normalized=pdmscOperationalNormalizePayload_(payload),impact=pdmscOperationalImpactPreview_(payload),lock=LockService.getDocumentLock();lock.waitLock(30000);try{const rows=pdmscOperationalRules_(),id=normalized.ruleId||('OPR-'+Utilities.getUuid().slice(0,8).toUpperCase()),old=rows.find(x=>x.ruleId===id),sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.OP_RULES),row=old?old.row:sh.getLastRow()+1,vals=[id,normalized.startDate,normalized.endDate,normalized.scopeType,normalized.scopeValue,normalized.action,normalized.cutoff,normalized.eventExemption,normalized.note,normalized.active,new Date(),normalized.outScanPolicy];sh.getRange(row,7).setNumberFormat('@');sh.getRange(row,1,1,vals.length).setValues([vals]);pdmscLog_(old?'OP_RULE_EDIT':'OP_RULE_SAVE','OK',{ruleId:id,before:old?{startDate:pdmscS01DateUi_(old.startDate),endDate:pdmscS01DateUi_(old.endDate),scopeType:old.scopeType,scopeValue:old.scopeValue,action:old.action,cutoff:old.cutoff,note:old.note}:null,after:{startDate:pdmscS01DateUi_(normalized.startDate),endDate:pdmscS01DateUi_(normalized.endDate),scopeType:normalized.scopeType,scopeValue:normalized.scopeValue,action:normalized.action,cutoff:normalized.cutoff,note:normalized.note},impact:{changedPersonDays:impact.changedPersonDays,activeFinalEvents:impact.activeFinalEvents}});return{ok:true,ruleId:id,impact};}finally{lock.releaseLock();}}
function pdmscOperationalSetActive_(ruleId,active){const x=pdmscOperationalRules_().find(r=>r.ruleId===ruleId);if(!x)throw new Error('ไม่พบ Rule '+ruleId);const sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.OP_RULES);sh.getRange(x.row,10).setValue(!!active);sh.getRange(x.row,11).setValue(new Date());pdmscLog_('OP_RULE_ACTIVE','OK',{ruleId,active:!!active});return{ok:true};}
function pdmscOperationalScopeV02SelfTest_(){const settings={LATE_CUTOFF:'07:51'},rules=[{row:1,ruleId:'BREAK',startDate:new Date(2026,3,5),endDate:new Date(2026,4,10),scopeType:'EXCEPT_GROUPS',scopeValue:'ลูกจ้าง',action:'IGNORE',cutoff:'',eventExemption:'NONE',active:true},{row:2,ruleId:'EMP',startDate:new Date(2026,3,6),endDate:new Date(2026,4,10),scopeType:'GROUP',scopeValue:'ลูกจ้าง | เจ้าหน้าที่',action:'LEAVE_ONLY',cutoff:'',eventExemption:'NONE',active:true},{row:3,ruleId:'APR7',startDate:new Date(2026,3,7),endDate:new Date(2026,3,7),scopeType:'ALL',scopeValue:'',action:'PROCESS',cutoff:'08:31',eventExemption:'NONE',active:true}],d6=new Date(2026,3,6),d7=new Date(2026,3,7),tests=[{name:'ทุกกลุ่มยกเว้น excludes selected group',ok:pdmscOperationalRuleFor_(d6,'วิทย์ฯ',rules,settings).action==='IGNORE'},{name:'เฉพาะกลุ่มหลายกลุ่ม matches ลูกจ้าง',ok:pdmscOperationalRuleFor_(d6,'ลูกจ้าง',rules,settings).action==='LEAVE_ONLY'},{name:'เฉพาะกลุ่มหลายกลุ่ม matches เจ้าหน้าที่',ok:pdmscOperationalRuleFor_(d6,'เจ้าหน้าที่',rules,settings).action==='LEAVE_ONLY'},{name:'วันเฉพาะชนะช่วงกว้าง',ok:pdmscOperationalRuleFor_(d7,'วิทย์ฯ',rules,settings).action==='PROCESS'&&pdmscOperationalRuleFor_(d7,'วิทย์ฯ',rules,settings).cutoff==='08:31'},{name:'legacy GROUP single value preserved',ok:pdmscOperationalScopeMatches_({scopeType:'GROUP',scopeValue:'ลูกจ้าง'},'ลูกจ้าง')},{name:'scope store round-trip',ok:pdmscOperationalScopeValues_(pdmscOperationalScopeStore_(['ไทย','วิทย์ฯ'])).length===2}];return{ok:tests.every(x=>x.ok),tests};}
