const PDMSC_WARNING_RULE=Object.freeze({
  VERSION:'W02-V0.2.0',
  METRIC:Object.freeze({COUNT:'COUNT',DAYS:'DAYS',MINUTES:'MINUTES'}),
  EVAL:Object.freeze({COUNT:'COUNT',TOTAL:'TOTAL',COUNT_OR_TOTAL:'COUNT_OR_TOTAL'}),
  WINDOWS:Object.freeze(['WEEKLY','MONTHLY','PERIOD_6M'])
});
function pdmscWarningRuleMetricAllowed_(category){const c=pdmscNormalizeText_(category).toUpperCase();if(c==='LEAVE')return['COUNT','DAYS'];if(c==='LATE')return['COUNT','MINUTES'];return['COUNT'];}
function pdmscWarningRuleDefaultTotalMetric_(category){return pdmscNormalizeText_(category).toUpperCase()==='LEAVE'?'DAYS':pdmscNormalizeText_(category).toUpperCase()==='LATE'?'MINUTES':'COUNT';}
function pdmscWarningRuleNormalizeMetric_(category,metric,evaluation){const e=pdmscNormalizeText_(evaluation).toUpperCase()||'COUNT';let m=pdmscNormalizeText_(metric).toUpperCase();if(e==='COUNT')m='COUNT';else if(!m||m==='COUNT')m=pdmscWarningRuleDefaultTotalMetric_(category);if(!pdmscWarningRuleMetricAllowed_(category).includes(m))throw new Error('Metric '+m+' ไม่รองรับกับ '+category);return m;}
function pdmscWarningRuleNormalizeEval_(value){const e=pdmscNormalizeText_(value).toUpperCase()||'COUNT';if(!Object.values(PDMSC_WARNING_RULE.EVAL).includes(e))throw new Error('วิธีประเมิน Warning ไม่รองรับ: '+e);return e;}
function pdmscWarningRuleDateKey_(v){if(v===''||v===null||v===undefined)return'';const d=pdmscS01Date_(v);if(!d)throw new Error('วันที่เริ่ม/สิ้นสุดกฎเตือนไม่ถูกต้อง');return Utilities.formatDate(d,PDMSC.TIMEZONE,'yyyyMMdd');}
function pdmscWarningRuleDate_(v){const k=pdmscWarningRuleDateKey_(v);return k?new Date(Number(k.slice(0,4)),Number(k.slice(4,6))-1,Number(k.slice(6,8)),12,0,0):null;}
function pdmscWarningRuleSelectorTokens_(r){const c=pdmscNormalizeText_(r.category).toUpperCase();if(c==='LEAVE'){const ids=String(r.includedTypeIds||'').split('|').map(pdmscNormalizeText_).filter(Boolean);if(ids.length)return ids.map(x=>x.toUpperCase());return String(r.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean).map(x=>'LEGACY:'+pdmscMasterNormalize_(x));}return String(r.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean).map(x=>x.toUpperCase());}
function pdmscWarningRuleRangeOverlap_(a,b){const as=a.effectiveStart?pdmscWarningRuleDateKey_(a.effectiveStart):'00000000',ae=a.effectiveEnd?pdmscWarningRuleDateKey_(a.effectiveEnd):'99999999',bs=b.effectiveStart?pdmscWarningRuleDateKey_(b.effectiveStart):'00000000',be=b.effectiveEnd?pdmscWarningRuleDateKey_(b.effectiveEnd):'99999999';return as<=be&&ae>=bs;}
function pdmscWarningRuleEventUniverse_(category){const c=pdmscNormalizeText_(category).toUpperCase();if(c==='LATE')return['LATE','LATE_AND_MISSING_OUT','HALF_LEAVE_PM_LATE'];if(c==='MISSING_SCAN')return['MISSING_IN','MISSING_OUT','MISSING_IN_OUT','LATE_AND_MISSING_OUT'];return[];}
function pdmscWarningRuleSelectorsOverlap_(a,b){const c=pdmscNormalizeText_(a.category).toUpperCase();if(c==='LEAVE'){const aa=new Set(pdmscWarningRuleSelectorTokens_(a)),bb=pdmscWarningRuleSelectorTokens_(b);return bb.some(x=>aa.has(x));}const as=String(a.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean),bs=String(b.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean);return pdmscWarningRuleEventUniverse_(c).some(t=>as.some(x=>pdmscA02EventSelectorMatch_(x,t,{}))&&bs.some(x=>pdmscA02EventSelectorMatch_(x,t,{})));}
function pdmscWarningRuleConflict_(candidate,rules){return (rules||[]).find(r=>r.ruleId!==candidate.ruleId&&r.active&&candidate.active&&pdmscNormalizeText_(r.category).toUpperCase()===pdmscNormalizeText_(candidate.category).toUpperCase()&&r.window===candidate.window&&pdmscWarningRuleRangeOverlap_(r,candidate)&&pdmscWarningRuleSelectorsOverlap_(r,candidate));}
function pdmscWarningRuleLeaveSelection_(payload){
  const idsRaw=String(payload.includedTypeIds||'').split('|').map(pdmscNormalizeText_).filter(Boolean),namesRaw=String(payload.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean),items=[];
  (idsRaw.length?idsRaw:namesRaw).forEach(v=>{const item=pdmscMasterResolveItem_('LEAVE_TYPE',v,true);if(!item)throw new Error('ไม่พบประเภทการลาใน Master: '+v);const pol=pdmscLeaveTypePolicyFor_(item.name);if(!pdmscLeaveCoreCountsTowardWarning_(item.name))throw new Error('ประเภทการลา “'+item.name+'” ไม่ได้เปิด “นับเข้าฐานการลาเพื่อเตือน” ที่ ตั้งค่า → การลา');if(!items.some(x=>x.id===item.id))items.push({id:item.id,name:item.name,policy:pol});});
  if(!items.length)throw new Error('กรุณาเลือกประเภทการลาที่ใช้ในกฎเตือนอย่างน้อย 1 รายการ');return items;
}
function pdmscWarningRuleNormalizePayload_(payload,existingRules){
  payload=payload||{};const category=pdmscNormalizeText_(payload.category).toUpperCase();if(!['LEAVE','LATE','MISSING_SCAN'].includes(category))throw new Error('ประเภทกฎเตือนไม่รองรับ');const evaluation=pdmscWarningRuleNormalizeEval_(payload.evaluationMode),metric=pdmscWarningRuleNormalizeMetric_(category,payload.metric,evaluation),threshold=Number(payload.threshold),secondary=Number(payload.secondaryThreshold||0),window=pdmscNormalizeText_(payload.window).toUpperCase();
  if(!Number.isFinite(threshold)||threshold<=0)throw new Error('เกณฑ์หลักต้องมากกว่า 0');if(!PDMSC_WARNING_RULE.WINDOWS.includes(window))throw new Error('รอบการนับไม่รองรับ');if(evaluation==='COUNT_OR_TOTAL'&&(!Number.isFinite(secondary)||secondary<=0))throw new Error('เกณฑ์ยอดรวมต้องมากกว่า 0 เมื่อใช้ “จำนวนครั้ง หรือ ยอดรวม”');if(evaluation==='TOTAL'&&metric==='COUNT')throw new Error('วิธีประเมินยอดรวมต้องใช้ DAYS หรือ MINUTES');if(category==='MISSING_SCAN'&&evaluation!=='COUNT')throw new Error('กฎไม่สแกนรองรับเกณฑ์จำนวนครั้งเท่านั้น');
  const effectiveStart=pdmscWarningRuleDate_(payload.effectiveStart),effectiveEnd=pdmscWarningRuleDate_(payload.effectiveEnd);if(effectiveStart&&effectiveEnd&&effectiveEnd<effectiveStart)throw new Error('วันที่สิ้นสุดกฎเตือนต้องไม่น้อยกว่าวันเริ่ม');
  let includedEventTypes='',includedTypeIds='';if(category==='LEAVE'){const items=pdmscWarningRuleLeaveSelection_(payload);includedEventTypes=items.map(x=>x.name).join(' | ');includedTypeIds=items.map(x=>x.id).join(' | ');}else{const allowed=String(payload.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean).map(x=>x.toUpperCase()),valid=category==='LATE'?new Set(['LATE','LATE_AND_MISSING_OUT','HALF_LEAVE_PM_LATE']):new Set(['MISSING_IN','MISSING_OUT','MISSING_IN_OUT','LATE_AND_MISSING_OUT']);const bad=allowed.filter(x=>!valid.has(x));if(bad.length)throw new Error('Event ไม่รองรับกับกฎ '+category+': '+bad.join(', '));includedEventTypes=[...new Set(allowed)].join(' | ');if(!includedEventTypes)throw new Error('กรุณาเลือกเหตุการณ์อย่างน้อย 1 รายการ');}
  const out={ruleId:pdmscNormalizeText_(payload.ruleId)||('WRN-'+Utilities.getUuid().slice(0,8).toUpperCase()),name:pdmscNormalizeText_(payload.name),category,includedEventTypes,threshold,window,active:payload.active===false?false:true,note:pdmscNormalizeText_(payload.note),version:pdmscNormalizeText_(payload.version||'1'),metric,evaluationMode:evaluation,secondaryThreshold:evaluation==='COUNT_OR_TOTAL'?secondary:0,includedTypeIds,effectiveStart,effectiveEnd};if(!out.name)throw new Error('กรุณากรอกชื่อกฎเตือน');const conflict=pdmscWarningRuleConflict_(out,existingRules||[]);if(conflict)throw new Error('กฎเตือนทับซ้อนกับ “'+conflict.name+'” ในประเภท/รอบ/เหตุการณ์เดียวกัน กรุณารวมเป็นกฎเดียว หรือปิดกฎเดิมก่อน');return out;
}
function pdmscWarningRules_(){return pdmscRows_(PDMSC.BACKEND.WARNING_RULES).map((r,i)=>({row:i+2,ruleId:pdmscNormalizeText_(r[0]),name:pdmscNormalizeText_(r[1]),category:pdmscNormalizeText_(r[2]).toUpperCase(),includedEventTypes:pdmscNormalizeText_(r[3]),threshold:Number(r[4])||0,window:pdmscNormalizeText_(r[5]).toUpperCase(),active:pdmscBool_(r[6]),note:pdmscNormalizeText_(r[7]),version:pdmscNormalizeText_(r[8])||'1',updatedAt:r[9]||'',metric:pdmscNormalizeText_(r[10]).toUpperCase()||'COUNT',evaluationMode:pdmscNormalizeText_(r[11]).toUpperCase()||'COUNT',secondaryThreshold:Number(r[12])||0,includedTypeIds:pdmscNormalizeText_(r[13]),effectiveStart:r[14]?pdmscS01Date_(r[14]):null,effectiveEnd:r[15]?pdmscS01Date_(r[15]):null})).filter(x=>x.ruleId);}
function pdmscWarningRuleSave_(payload){const lock=LockService.getDocumentLock();lock.waitLock(30000);try{const rows=pdmscWarningRules_(),x=pdmscWarningRuleNormalizePayload_(payload,rows),old=rows.find(r=>r.ruleId===x.ruleId),sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.WARNING_RULES),vals=[x.ruleId,x.name,x.category,x.includedEventTypes,x.threshold,x.window,x.active,x.note,x.version,new Date(),x.metric,x.evaluationMode,x.secondaryThreshold,x.includedTypeIds,x.effectiveStart||'',x.effectiveEnd||''];if(old)sh.getRange(old.row,1,1,vals.length).setValues([vals]);else sh.appendRow(vals);pdmscWebCacheClear_(['settings-tab-warning','warning-candidates','statistics']);pdmscLog_('WARNING_RULE_SAVE','OK',{ruleId:x.ruleId,metric:x.metric,evaluationMode:x.evaluationMode,includedTypeIds:x.includedTypeIds});return{ok:true,ruleId:x.ruleId};}finally{lock.releaseLock();}}
function pdmscWarningRuleSetActive_(ruleId,active){const x=pdmscWarningRules_().find(r=>r.ruleId===ruleId);if(!x)throw new Error('ไม่พบ Warning Rule '+ruleId);if(active){const candidate=Object.assign({},x,{active:true}),conflict=pdmscWarningRuleConflict_(candidate,pdmscWarningRules_());if(conflict)throw new Error('เปิดกฎไม่ได้ เพราะทับซ้อนกับ “'+conflict.name+'”');}const sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.WARNING_RULES);sh.getRange(x.row,7).setValue(!!active);sh.getRange(x.row,10).setValue(new Date());pdmscWebCacheClear_(['settings-tab-warning','warning-candidates']);return{ok:true};}
function pdmscWarningRuleMigrateV020_(){const sh=SpreadsheetApp.getActive().getSheetByName(PDMSC.BACKEND.WARNING_RULES);if(!sh||sh.getLastRow()<2)return{updated:0,total:0,unresolved:[]};const n=sh.getLastRow()-1,cols=Math.max(16,sh.getLastColumn()),vals=sh.getRange(2,1,n,cols).getValues(),unresolved=[];let updated=0;vals.forEach((r,i)=>{let changed=false;const category=pdmscNormalizeText_(r[2]).toUpperCase();if(!pdmscNormalizeText_(r[10])){r[10]='COUNT';changed=true;}if(!pdmscNormalizeText_(r[11])){r[11]='COUNT';changed=true;}if(r[12]===''||r[12]===null){r[12]=0;changed=true;}if(category==='LEAVE'&&!pdmscNormalizeText_(r[13])){const names=String(r[3]||'').split('|').map(pdmscNormalizeText_).filter(Boolean),items=[];names.forEach(name=>{const item=pdmscMasterResolveItem_('LEAVE_TYPE',name,true);if(item&&!items.some(x=>x.id===item.id))items.push(item);else if(!item)unresolved.push({row:i+2,ruleId:pdmscNormalizeText_(r[0]),value:name});});if(items.length===names.length&&items.length){r[13]=items.map(x=>x.id).join(' | ');r[3]=items.map(x=>x.name).join(' | ');changed=true;}}if(changed){r[9]=new Date();updated++;}});if(updated)sh.getRange(2,1,n,cols).setValues(vals);return{updated,total:n,unresolved};}
function pdmscWarningRuleSelfTest_(){
  const leave={ruleId:'A',name:'ลา',category:'LEAVE',includedEventTypes:'ลาป่วย',includedTypeIds:'LVE001',threshold:2,window:'MONTHLY',active:true,metric:'COUNT',evaluationMode:'COUNT',secondaryThreshold:0,effectiveStart:null,effectiveEnd:null},same=Object.assign({},leave,{ruleId:'B'}),late={ruleId:'C',name:'สาย',category:'LATE',includedEventTypes:'LATE',includedTypeIds:'',threshold:3,window:'MONTHLY',active:true,metric:'COUNT',evaluationMode:'COUNT',secondaryThreshold:0,effectiveStart:null,effectiveEnd:null},lateCombo=Object.assign({},late,{ruleId:'D',includedEventTypes:'LATE_AND_MISSING_OUT'}),range={effectiveStart:new Date(2026,3,1,0),effectiveEnd:new Date(2026,3,3,0)};
  const tests=[
    {name:'same active selector conflicts',ok:!!pdmscWarningRuleConflict_(same,[leave])},
    {name:'facet-overlap active selector conflicts',ok:!!pdmscWarningRuleConflict_(lateCombo,[late])},
    {name:'different category does not conflict',ok:!pdmscWarningRuleConflict_(late,[leave])},
    {name:'LEAVE allows DAYS metric',ok:pdmscWarningRuleMetricAllowed_('LEAVE').includes('DAYS')},
    {name:'LATE allows MINUTES metric',ok:pdmscWarningRuleMetricAllowed_('LATE').includes('MINUTES')},
    {name:'MISSING scan stays count only',ok:pdmscWarningRuleMetricAllowed_('MISSING_SCAN').length===1},
    {name:'warning range uses date-only inclusive end',ok:pdmscWarningRuleDateKey_(range.effectiveEnd)==='20260403'&&pdmscWarningRuleRangeOverlap_(range,{effectiveStart:new Date(2026,3,3,12),effectiveEnd:new Date(2026,3,3,12)})},
    {name:'day after warning range does not overlap',ok:!pdmscWarningRuleRangeOverlap_(range,{effectiveStart:new Date(2026,3,4,0),effectiveEnd:new Date(2026,3,4,0)})}
  ];return{ok:tests.every(x=>x.ok),tests};
}
function pdmscWarningExcludedDepartmentIds_(){const raw=pdmscSettingsGet_('WARNING_EXCLUDED_GROUPS',''),out=new Set();String(raw||'').split('|').map(pdmscNormalizeText_).filter(Boolean).forEach(v=>{const item=pdmscMasterResolveItem_('DEPARTMENT',v,true);if(item)out.add(item.id);});return out;}
function pdmscWarningExcludedDepartmentNames_(){const ids=pdmscWarningExcludedDepartmentIds_(),names=[];ids.forEach(id=>{const x=pdmscMasterById_('DEPARTMENT',id,true);if(x)names.push(x.name);});return names;}
function pdmscWarningMigrateExcludedGroupsToIds_(){const raw=pdmscSettingsGet_('WARNING_EXCLUDED_GROUPS',''),tokens=String(raw||'').split('|').map(pdmscNormalizeText_).filter(Boolean),ids=[],unresolved=[];tokens.forEach(v=>{const item=pdmscMasterResolveItem_('DEPARTMENT',v,true);if(item){if(!ids.includes(item.id))ids.push(item.id);}else unresolved.push(v);});const canonical=ids.join(' | ');if(!unresolved.length&&canonical!==tokens.join(' | '))pdmscSettingsUpsert_('WARNING_EXCLUDED_GROUPS',canonical,'W02 migrate group policy to Department IDs');return{updated:!unresolved.length&&canonical!==tokens.join(' | '),ids,unresolved};}
