const PDMSC_STAT_S01=Object.freeze({VERSION:'S01-V0.2.6-WARNING-CONTRACT',CACHE_SECONDS:180,PAGE_SIZE_DEFAULT:50,PAGE_SIZE_MAX:200});

function pdmscStatisticsEventLabel_(t){return pdmscA03EventLabel_(t||'');}
function pdmscStatisticsMonthBounds_(monthKey){const k=pdmscNormalizeMonthKey_(monthKey),y=Number(k.slice(0,4)),m=Number(k.slice(4,6));return{start:new Date(y,m-1,1,12,0,0),end:new Date(y,m,0,12,0,0)};}
function pdmscStatisticsDateKey_(v){if(v instanceof Date)return Utilities.formatDate(v,PDMSC.TIMEZONE,'yyyyMMdd');const s=pdmscNormalizeText_(v).replace(/[^0-9]/g,'');if(/^\d{8}/.test(s))return s.slice(0,8);const d=pdmscS01Date_(v);return d?Utilities.formatDate(d,PDMSC.TIMEZONE,'yyyyMMdd'):'';}
function pdmscStatisticsDateUi_(v){const k=pdmscStatisticsDateKey_(v);if(!/^\d{8}$/.test(k))return'';return k.slice(6,8)+'/'+k.slice(4,6)+'/'+String(Number(k.slice(0,4))+543);}
function pdmscStatisticsDateFromKey_(k){const s=String(k||'').replace(/[^0-9]/g,'').slice(0,8);if(!/^\d{8}$/.test(s))return null;const d=new Date(Number(s.slice(0,4)),Number(s.slice(4,6))-1,Number(s.slice(6,8)),12,0,0);return isNaN(d)?null:d;}
function pdmscStatisticsPersonInMonth_(p,monthKey){const b=pdmscStatisticsMonthBounds_(monthKey),start=p.employmentStartDate?pdmscS01Date_(p.employmentStartDate):null,end=p.employmentEndDate?pdmscS01Date_(p.employmentEndDate):null;if(start&&start>b.end)return false;if(end&&end<b.start)return false;return !!p.active||!!start||!!end;}
function pdmscStatisticsPolicyForActive_(a){return pdmscDecisionPolicy((a&&a.decision)||PDMSC.DECISION.NORMAL);}
function pdmscStatisticsEventDetail_(a,person){const e=a.evidence||{},scan=e.scan||{},op=e.operational||{},cls=e.classification||{},dec=e.decision||{};return{eventIdentity:pdmscA03EventIdentityFromActive_(a),eventId:a.eventId||'',monthKey:a.monthKey||'',empId:a.empId||'',name:person.fullName||'',department:person.department||'',position:person.position||'',dateKey:pdmscStatisticsDateKey_(a.eventDate),date:pdmscStatisticsDateUi_(a.eventDate),eventType:a.eventType||'',eventLabel:pdmscStatisticsEventLabel_(a.eventType||''),decision:a.decision||PDMSC.DECISION.NORMAL,decisionLabel:pdmscA03DecisionLabel_(a.decision||PDMSC.DECISION.NORMAL),scanIn:scan.scanIn||'',scanOut:scan.scanOut||'',lateMinutes:Number(scan.lateMinutes)||0,reason:cls.reason||'',cutoff:op.cutoff||'',ruleId:op.ruleId||'',decisionNote:dec.note||''};}
function pdmscStatisticsLeaveDetail_(x,person){const policy=pdmscLeaveTypePolicyFor_(x.leaveType);return{leaveId:x.leaveId,empId:x.empId,name:person.fullName||x.empId,department:person.department||'',position:person.position||'',leaveType:x.leaveType,policy:{id:policy.id||'',countOccurrence:!!policy.countOccurrence,countDays:!!policy.countDays,includeWarningBase:!!policy.includeWarningBase,showSeparateStatistics:!!policy.showSeparateStatistics},start:pdmscLeaveDateUi_(x.start),end:pdmscLeaveDateUi_(x.end),days:x.days,monthDays:x.statsMonthDays,requestCount:x.statsRequestCount,rawMonthDays:x.monthDays,rawRequestCount:x.requestCount,warningMonthDays:x.warningMonthDays,warningRequestCount:x.warningRequestCount,allocation:x.allocation,allocationNeedsReview:!!x.effectiveAllocationNeedsReview,sourceNote:x.sourceNote||''};}
function pdmscStatisticsBlankPerson_(p,id){return{empId:p.empId||id,name:p.fullName||id,department:p.department||'',position:p.position||'',active:!!p.active,total:0,attendanceTotal:0,leaveRequests:0,leaveDays:0,warningLeaveRequests:0,warningLeaveDays:0,leaveNeedsReview:0,leaveByType:{},counts:{}};}
function pdmscStatisticsDataset_(monthKey,force){
  monthKey=pdmscNormalizeMonthKey_(monthKey);const cacheKey='statistics-'+monthKey;if(!force&&typeof pdmscWebCacheGet_==='function'){const c=pdmscWebCacheGet_(cacheKey);if(c)return c;}
  const started=Date.now(),people=pdmscGetPersonnelList('',true).filter(p=>pdmscStatisticsPersonInMonth_(p,monthKey)),pmap=new Map(people.map(p=>[pdmscNormalizeText_(p.empId).toUpperCase(),p])),active=pdmscA03ActiveRows_(monthKey),byType={},counted=[],excluded=[],keepStats=[];
  active.forEach(a=>{const policy=pdmscStatisticsPolicyForActive_(a);if(!policy.countStatistics){excluded.push(a);return;}counted.push(a);if(a.decision===PDMSC.DECISION.EXCLUDED_KEEP_STATS)keepStats.push(a);if(a.eventType!=='FULL_LEAVE')pdmscA03AddCount_(byType,a.eventType);});
  const leaveFacts=pdmscLeaveCoreEffectiveMonthFacts_(monthKey,active),warningLeaveFacts=pdmscLeaveCoreWarningBaseFromEffectiveFacts_(leaveFacts),leaveDetails=leaveFacts.map(x=>pdmscStatisticsLeaveDetail_(x,pmap.get(pdmscNormalizeText_(x.empId).toUpperCase())||{}));
  const per=new Map();people.forEach(p=>per.set(pdmscNormalizeText_(p.empId).toUpperCase(),pdmscStatisticsBlankPerson_(p,p.empId)));
  counted.filter(a=>a.eventType!=='FULL_LEAVE').forEach(a=>{const id=pdmscNormalizeText_(a.empId).toUpperCase(),p=pmap.get(id)||{empId:id,fullName:id,department:'',position:'',active:true};if(!per.has(id))per.set(id,pdmscStatisticsBlankPerson_(p,id));const x=per.get(id);x.attendanceTotal++;pdmscA03AddCount_(x.counts,a.eventType);});
  leaveDetails.forEach(l=>{const id=pdmscNormalizeText_(l.empId).toUpperCase();if(!per.has(id)){const p=pmap.get(id)||{empId:id,fullName:id,department:'',position:'',active:true};per.set(id,pdmscStatisticsBlankPerson_(p,id));}const x=per.get(id),req=l.policy.countOccurrence?Number(l.requestCount||0):0,days=l.policy.countDays?(l.monthDays===null?0:Number(l.monthDays||0)):0,key=pdmscMasterNormalize_(l.leaveType);if(!x.leaveByType[key])x.leaveByType[key]={name:l.leaveType,requests:0,days:0,includeWarningBase:!!l.policy.includeWarningBase,showSeparateStatistics:!!l.policy.showSeparateStatistics};x.leaveByType[key].requests+=req;x.leaveByType[key].days+=days;x.leaveRequests+=req;x.leaveDays+=days;if(l.policy.includeWarningBase){x.warningLeaveRequests+=l.policy.countOccurrence?Number(l.warningRequestCount||0):0;x.warningLeaveDays+=l.policy.countDays&&l.warningMonthDays!==null?Number(l.warningMonthDays||0):0;}if(l.allocationNeedsReview)x.leaveNeedsReview++;});
  const personRows=Array.from(per.values()).map(x=>{x.total=x.attendanceTotal+x.leaveRequests;x.hasActivity=x.attendanceTotal>0||x.leaveRequests>0||x.leaveDays>0;return x;}).sort((a,b)=>a.name.localeCompare(b.name,'th'));
  const eventDetails=counted.filter(a=>a.eventType!=='FULL_LEAVE').map(a=>pdmscStatisticsEventDetail_(a,pmap.get(pdmscNormalizeText_(a.empId).toUpperCase())||{})).sort((a,b)=>a.dateKey.localeCompare(b.dateKey)||a.name.localeCompare(b.name,'th'));
  const lateDetails=eventDetails.filter(x=>pdmscA02EventFacets_(x.eventType,{scan:{lateMinutes:x.lateMinutes}}).late),officialDutyDetails=eventDetails.filter(x=>pdmscA02EventFacets_(x.eventType,{}).officialDuty);
  const departments=[...new Set(personRows.map(x=>x.department).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th')),eventTypes=[...new Set(counted.filter(a=>a.eventType!=='FULL_LEAVE').map(x=>x.eventType).filter(Boolean))].sort(),leavePolicies=pdmscLeaveTypePolicyList_(false),leaveTypes=leavePolicies.map(x=>x.name).sort((a,b)=>a.localeCompare(b,'th'));
  const warningBase=pdmscLeaveCoreWarningBaseSummaryFromEffectiveFacts_(leaveFacts,monthKey);
  const leaveSummary={requests:leaveDetails.reduce((s,x)=>s+(x.policy.countOccurrence?Number(x.requestCount||0):0),0),days:leaveDetails.reduce((s,x)=>s+(x.policy.countDays&&x.monthDays!==null?Number(x.monthDays||0):0),0),warningRequests:Number(warningBase.requests||0),warningDays:Number(warningBase.days||0),warningNeedsReview:Number(warningBase.needsReview||0),needsReview:leaveDetails.filter(x=>x.allocationNeedsReview).length,byType:{}};
  leaveDetails.forEach(x=>{const k=pdmscMasterNormalize_(x.leaveType);if(!leaveSummary.byType[k])leaveSummary.byType[k]={name:x.leaveType,requests:0,days:0,includeWarningBase:!!x.policy.includeWarningBase,showSeparateStatistics:!!x.policy.showSeparateStatistics};if(x.policy.countOccurrence)leaveSummary.byType[k].requests+=Number(x.requestCount||0);if(x.policy.countDays&&x.monthDays!==null)leaveSummary.byType[k].days+=Number(x.monthDays||0);});
  const leaveGroupMap=new Map();
  leaveDetails.forEach(x=>{const k=x.empId+'|'+x.leaveType,z=leaveGroupMap.get(k)||{empId:x.empId,name:x.name,department:x.department,leaveType:x.leaveType,requests:0,days:0,includeWarningBase:!!x.policy.includeWarningBase,showSeparateStatistics:!!x.policy.showSeparateStatistics,needsReview:0};if(x.policy.countOccurrence)z.requests+=Number(x.requestCount||0);if(x.policy.countDays&&x.monthDays!==null)z.days+=Number(x.monthDays||0);if(x.allocationNeedsReview)z.needsReview++;leaveGroupMap.set(k,z);});
  const leaveGroupRows=[...leaveGroupMap.values()].sort((a,b)=>a.name.localeCompare(b.name,'th')||a.leaveType.localeCompare(b.leaveType,'th'));
  const latePersonMap=new Map();
  lateDetails.forEach(x=>{const z=latePersonMap.get(x.empId)||{empId:x.empId,name:x.name,department:x.department,late:0,lateMissing:0,totalLate:0,minutes:0};if(x.eventType==='LATE')z.late++;else if(x.eventType==='LATE_AND_MISSING_OUT')z.lateMissing++;z.totalLate++;z.minutes+=Number(x.lateMinutes||0);latePersonMap.set(x.empId,z);});
  const latePersonRows=[...latePersonMap.values()].sort((a,b)=>b.totalLate-a.totalLate||a.name.localeCompare(b.name,'th'));
  const officialPersonMap=new Map();
  officialDutyDetails.forEach(x=>{const z=officialPersonMap.get(x.empId)||{empId:x.empId,name:x.name,department:x.department,occurrences:0,dateKeys:[]},seen=new Set(z.dateKeys);z.occurrences++;if(x.dateKey&&!seen.has(x.dateKey))z.dateKeys.push(x.dateKey);officialPersonMap.set(x.empId,z);});
  const officialPersonRows=[...officialPersonMap.values()].map(x=>Object.assign({},x,{days:x.dateKeys.length})).sort((a,b)=>b.occurrences-a.occurrences||a.name.localeCompare(b.name,'th'));
  const out=pdmscWebSafe_({ok:true,version:PDMSC_STAT_S01.VERSION,monthKey,label:pdmscWebMonthLabel_(monthKey),summary:{personnel:personRows.length,peopleWithEvents:personRows.filter(x=>x.hasActivity).length,countedEvents:eventDetails.length,excludedEvents:excluded.length,keepStatsEvents:keepStats.length,activeEvents:active.length,byType,leave:leaveSummary,officialDuty:{occurrences:officialDutyDetails.length,days:new Set(officialDutyDetails.map(x=>x.empId+'|'+x.dateKey)).size}},filters:{departments,eventTypes:eventTypes.map(t=>({key:t,label:pdmscStatisticsEventLabel_(t)})),leaveTypes,leavePolicies},personRows,eventDetails,lateDetails,officialDutyDetails,leaveDetails,leaveGroupRows,latePersonRows,officialPersonRows,serverMs:Date.now()-started});
  if(typeof pdmscWebCachePut_==='function')pdmscWebCachePut_(cacheKey,out,PDMSC_STAT_S01.CACHE_SECONDS);return out;
}

function pdmscStatisticsAggregateLeaveDetails_(details){const g={};(details||[]).forEach(d=>{const k=d.type||d.leaveType||'การลา';if(!g[k])g[k]={name:k,count:0,days:0};g[k].count+=Number(d.count||d.requests||0);g[k].days+=Number(d.days||0);});return Object.keys(g).map(k=>g[k]);}
function pdmscStatisticsPeriodMetricBundle_(){const p=pdmscGetActivePeriod(),months=p.months||[],decisions=typeof pdmscA022LatestDecisionIndex_==='function'?pdmscA022LatestDecisionIndex_():new Map(),active=months.length?pdmscA03ActiveRowsForMonths_(months,decisions):[],leaveFacts=months.length?pdmscLeaveCoreEffectiveFactsForMonths_(months,active):{},people=pdmscGetPersonnelList('',true),pmap=new Map(people.map(x=>[String(x.empId||'').toUpperCase(),x]));return{period:p,months,active,leaveFacts,people,pmap};}
function pdmscStatisticsLeavePersonMetricFromFacts_(facts,months,empId,asOf,person){
  const id=String(empId||'').toUpperCase(),endKey=asOf?pdmscStatisticsDateKey_(asOf):'',details=[];let count=0,days=0;
  (months||[]).forEach(m=>(facts&&facts[m]||[]).filter(x=>String(x.empId||'').toUpperCase()===id).forEach(x=>{
    const anchor=x.effectiveOccurrenceDateKey||pdmscLeaveDateKey_(x.start),req=Number(x.statsRequestCount||0),extra=Number(x.carryInExtraDays||0),rows=(x.dateRows||[]),eligibleRows=rows.filter(r=>(!endKey||String(r.dateKey||'')<=endKey)&&!!r.countStatistics),anchorRow=rows.find(r=>r.dateKey===anchor),canCountOccurrence=req>0&&eligibleRows.length>0&&(!endKey||anchor<=endKey);let occurrencePlaced=false;
    const leaveId=String(x.leaveId||''),leaveStartKey=x.start?pdmscStatisticsDateKey_(x.start):'',leaveEndKey=x.end?pdmscStatisticsDateKey_(x.end):'';
    rows.forEach(r=>{if(endKey&&String(r.dateKey||'')>endKey)return;if(!r.countStatistics)return;let rd=r.days===null?0:Number(r.days||0),rc=0;if(canCountOccurrence&&r.dateKey===anchor&&!occurrencePlaced){rc=req;occurrencePlaced=true;}if(r.dateKey===anchor&&anchorRow&&anchorRow.countStatistics)rd+=extra;count+=rc;days+=rd;details.push({dateKey:r.dateKey,date:pdmscStatisticsDateUi_(r.dateKey),type:x.leaveType,count:rc,days:rd,minutes:0,note:x.sourceNote||'',leaveId,leaveStartKey,leaveEndKey});});
    if(canCountOccurrence&&!occurrencePlaced){count+=req;details.push({dateKey:anchor,date:pdmscStatisticsDateUi_(anchor),type:x.leaveType,count:req,days:0,minutes:0,note:x.sourceNote||'',leaveId,leaveStartKey,leaveEndKey});}
  }));
  details.sort((a,b)=>a.dateKey.localeCompare(b.dateKey)||String(a.type||'').localeCompare(String(b.type||''),'th'));return{count,days,minutes:0,details,person:person||{}};
}
function pdmscStatisticsPersonMetricFromBundle_(bundle,empId,category,asOf){
  bundle=bundle||pdmscStatisticsPeriodMetricBundle_();const months=bundle.months||[],active=bundle.active||[],endKey=asOf?pdmscStatisticsDateKey_(asOf):'',id=String(empId||'').toUpperCase(),person=bundle.pmap.get(id)||{};
  if(category==='LEAVE')return pdmscStatisticsLeavePersonMetricFromFacts_(bundle.leaveFacts||{},months,id,asOf,person);
  let count=0,minutes=0;const details=[];active.forEach(a=>{if(String(a.empId||'').toUpperCase()!==id)return;const dateKey=pdmscStatisticsDateKey_(a.eventDate);if(endKey&&dateKey>endKey)return;const pol=pdmscDecisionPolicy(a.decision||PDMSC.DECISION.NORMAL);if(!pol.countStatistics)return;const evidence=a.evidence||{},f=pdmscA02EventFacets_(a.eventType,evidence);if(category==='LATE'&&f.late){const scan=evidence.scan||{},op=evidence.operational||{},lateMinutes=Number(f.lateMinutes||0);count++;minutes+=lateMinutes;details.push({dateKey,date:pdmscStatisticsDateUi_(dateKey),type:'มาสาย',count:1,days:0,minutes:lateMinutes,scanIn:String(scan.scanIn||''),scanOut:String(scan.scanOut||''),cutoff:String(op.cutoff||''),ruleId:String(op.cutoffRuleId||op.ruleId||''),note:(evidence.classification||{}).reason||''});}});details.sort((a,b)=>a.dateKey.localeCompare(b.dateKey));return{count,days:0,minutes,details,person};
}
function pdmscStatisticsMetricSlice_(metric,start,end){const sk=start?pdmscStatisticsDateKey_(start):'',ek=end?pdmscStatisticsDateKey_(end):'',rows=(metric&&metric.details||[]).filter(d=>(!sk||d.dateKey>=sk)&&(!ek||d.dateKey<=ek));return{count:rows.reduce((s,d)=>s+Number(d.count||0),0),days:rows.reduce((s,d)=>s+Number(d.days||0),0),minutes:rows.reduce((s,d)=>s+Number(d.minutes||0),0),details:rows};}
function pdmscStatisticsPersonMetric_(empId,category,asOf){return pdmscStatisticsPersonMetricFromBundle_(pdmscStatisticsPeriodMetricBundle_(),empId,category,asOf);}

function pdmscStatisticsBootstrap_(){const period=pdmscWebPeriodView_(),months=period.months||[],defaultMonth=months.length?months[months.length-1].key:'';return pdmscWebSafe_({ok:true,version:PDMSC_STAT_S01.VERSION,period,defaultMonth,loaded:false});}
function pdmscStatisticsSelfTest_(){
  const policies=[pdmscDecisionPolicy(PDMSC.DECISION.NORMAL),pdmscDecisionPolicy(PDMSC.DECISION.EXCLUDED),pdmscDecisionPolicy(PDMSC.DECISION.EXCLUDED_KEEP_STATS)],leave=pdmscLeaveCoreSelfTest_(),sick=pdmscLeaveTypePolicyDefault_('ลาป่วย'),other=pdmscLeaveTypePolicyDefault_('ลาอุปสมบท'),carry=pdmscStatisticsLeavePersonMetricFromFacts_({'202604':[{leaveId:'L-CARRY',empId:'E1',leaveType:'ลาป่วย',start:new Date(2026,2,31),end:new Date(2026,3,1),effectiveOccurrenceDateKey:'20260401',statsRequestCount:1,carryInExtraDays:1,dateRows:[{dateKey:'20260401',days:1,countStatistics:true}],sourceNote:'carry'}]},['202604'],'E1',new Date(2026,3,1),{}),excluded=pdmscStatisticsLeavePersonMetricFromFacts_({'202604':[{empId:'E1',leaveType:'ลาป่วย',effectiveOccurrenceDateKey:'20260401',statsRequestCount:0,carryInExtraDays:1,dateRows:[{dateKey:'20260401',days:1,countStatistics:false}],sourceNote:'excluded'}]},['202604'],'E1',new Date(2026,3,1),{}),tests=[
    {name:'NORMAL counts statistics',ok:policies[0].countStatistics===true},{name:'EXCLUDED does not count statistics',ok:policies[1].countStatistics===false&&policies[1].allowWarning===false},{name:'EXCLUDED_KEEP_STATS counts statistics but blocks warning',ok:policies[2].countStatistics===true&&policies[2].allowWarning===false},{name:'Statistics uses ACTIVE Final Event reader',ok:typeof pdmscA03ActiveRows_==='function'},{name:'Statistics uses effective Leave Core facts',ok:typeof pdmscLeaveCoreEffectiveMonthFacts_==='function'},{name:'Leave Core allocation self-test',ok:leave.ok},{name:'Leave policy source is existing Leave Type Master',ok:typeof pdmscLeaveTypePolicyFor_==='function'&&typeof pdmscLeaveTypePolicyList_==='function'},{name:'Safe default: sick leave warning base',ok:sick.includeWarningBase===true},{name:'Safe default: unknown leave not warning base',ok:other.includeWarningBase===false},{name:'Official Duty stays event source, not leave source',ok:pdmscA02EventFacets_('OFFICIAL_DUTY',{}).officialDuty===true},{name:'Half-leave PM late is visible in late statistics',ok:pdmscA02EventFacets_('HALF_LEAVE_PM_LATE',{scan:{lateMinutes:5}}).late===true},{name:'Month scope is explicit',ok:pdmscNormalizeMonthKey_('202604')==='202604'},{name:'Canonical period metric API exists for downstream Document',ok:typeof pdmscStatisticsPeriodMetricBundle_==='function'&&typeof pdmscStatisticsPersonMetricFromBundle_==='function'&&typeof pdmscStatisticsMetricSlice_==='function'},{name:'Statistics Core has no reverse dependency on Warning date helpers',ok:pdmscStatisticsPersonMetricFromBundle_.toString().indexOf('pdmscWarningDate')<0&&pdmscStatisticsMetricSlice_.toString().indexOf('pdmscWarningDate')<0&&pdmscStatisticsLeavePersonMetricFromFacts_.toString().indexOf('pdmscWarningDate')<0},{name:'Carry-in 31 Mar–1 Apr stays 1 occurrence / 2 days',ok:carry.count===1&&carry.days===2},{name:'Canonical leave detail carries original Leave ID/start/end metadata',ok:carry.details.length===1&&carry.details[0].leaveId==='L-CARRY'&&carry.details[0].leaveStartKey==='20260331'&&carry.details[0].leaveEndKey==='20260401'},{name:'EXCLUDED leave does not leak into canonical document metric',ok:excluded.count===0&&excluded.days===0}
  ];return{ok:tests.every(t=>t.ok),tests,leaveSelfTest:leave};
}
