const PDMSC_WARNING_CANDIDATE = Object.freeze({VERSION:'W02-V0.2.2',CACHE_SECONDS:180});
function pdmscWarningDateKey_(v){if(v instanceof Date&&!isNaN(v.getTime()))return Utilities.formatDate(v,PDMSC.TIMEZONE,'yyyyMMdd');const d=pdmscS01Date_(v);return d?Utilities.formatDate(d,PDMSC.TIMEZONE,'yyyyMMdd'):'';}
function pdmscWarningDateFromKey_(k){return new Date(Number(k.slice(0,4)),Number(k.slice(4,6))-1,Number(k.slice(6,8)),12,0,0);}
function pdmscWarningDayIndex_(name){const n=pdmscNormalizeText_(name).toLowerCase(),m={'อาทิตย์':0,'วันอาทิตย์':0,'sunday':0,'sun':0,'จันทร์':1,'วันจันทร์':1,'monday':1,'mon':1,'อังคาร':2,'วันอังคาร':2,'tuesday':2,'tue':2,'พุธ':3,'วันพุธ':3,'wednesday':3,'wed':3,'พฤหัสบดี':4,'วันพฤหัสบดี':4,'พฤหัส':4,'thursday':4,'thu':4,'ศุกร์':5,'วันศุกร์':5,'friday':5,'fri':5,'เสาร์':6,'วันเสาร์':6,'saturday':6,'sat':6};return Object.prototype.hasOwnProperty.call(m,n)?m[n]:1;}
function pdmscWarningWeekRangeForDate_(date,startName,endName){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate(),12),si=pdmscWarningDayIndex_(startName),ei=pdmscWarningDayIndex_(endName),back=(d.getDay()-si+7)%7,start=new Date(d);start.setDate(start.getDate()-back);const span=(ei-si+7)%7,end=new Date(start);end.setDate(end.getDate()+span);return{start,end,key:Utilities.formatDate(start,PDMSC.TIMEZONE,'yyyyMMdd')+'-'+Utilities.formatDate(end,PDMSC.TIMEZONE,'yyyyMMdd')};}
function pdmscWarningRangeLabel_(a,b){return pdmscStatisticsDateUi_(a)+' → '+pdmscStatisticsDateUi_(b);}
function pdmscWarningNeededMonths_(selectedMonth,rules,period){const months=(period.months||[]).map(x=>x.key),need=new Set([selectedMonth]),idx=months.indexOf(selectedMonth);if(rules.some(r=>r.window==='PERIOD_6M'))months.forEach(x=>need.add(x));if(rules.some(r=>r.window==='WEEKLY')){if(idx>0)need.add(months[idx-1]);if(idx>=0&&idx<months.length-1)need.add(months[idx+1]);}return months.filter(x=>need.has(x));}
function pdmscWarningItemWithinRuleRange_(rule,date){const dk=pdmscWarningDateKey_(date),sk=rule.effectiveStart?pdmscWarningRuleDateKey_(rule.effectiveStart):'',ek=rule.effectiveEnd?pdmscWarningRuleDateKey_(rule.effectiveEnd):'';if(!dk)return false;if(sk&&dk<sk)return false;if(ek&&dk>ek)return false;return true;}
function pdmscWarningSourceBundle_(months){
  const started=Date.now(),people=pdmscGetPersonnelList('',true),pmap=new Map(people.map(p=>[pdmscNormalizeText_(p.empId).toUpperCase(),p])),depItems=pdmscMasterList_('DEPARTMENT',true),depByName=new Map();depItems.forEach(x=>{depByName.set(pdmscMasterNormalize_(x.name),x);(x.aliasList||[]).forEach(a=>depByName.set(pdmscMasterNormalize_(a),x));});
  const decisionIndex=typeof pdmscA022LatestDecisionIndex_==='function'?pdmscA022LatestDecisionIndex_():new Map();
  if(typeof pdmscA03ActiveRowsForMonths_!=='function')throw new Error('Final Event bulk reader ไม่พร้อม: ต้องมี pdmscA03ActiveRowsForMonths_ ก่อนใช้ Warning W02 V0.2.1');
  const activeEvents=pdmscA03ActiveRowsForMonths_(months,decisionIndex),events=[];
  activeEvents.forEach(a=>{const pol=pdmscDecisionPolicy(a.decision||PDMSC.DECISION.NORMAL);if(!pol.allowWarning)return;const p=pmap.get(pdmscNormalizeText_(a.empId).toUpperCase())||{},dep=depByName.get(pdmscMasterNormalize_(p.department||''))||{},facets=pdmscA02EventFacets_(a.eventType,a.evidence||{});events.push({empId:a.empId,name:p.fullName||a.empId,department:p.department||'',departmentId:dep.id||'',dateKey:pdmscWarningDateKey_(a.eventDate),eventType:a.eventType,evidence:a.evidence||{},facets,decision:a.decision||PDMSC.DECISION.NORMAL,eventIdentity:pdmscA03EventIdentityFromActive_(a)});});
  const effectiveByMonth=pdmscLeaveCoreEffectiveFactsForMonths_(months,activeEvents),leave=[];
  months.forEach(m=>(effectiveByMonth[m]||[]).forEach(x=>{if(!pdmscLeaveCoreCountsTowardWarning_(x.leaveType))return;const p=pmap.get(pdmscNormalizeText_(x.empId).toUpperCase())||{},dep=depByName.get(pdmscMasterNormalize_(p.department||''))||{},policy=pdmscLeaveTypePolicyFor_(x.leaveType),flags=pdmscLeaveCorePolicyFlags_(policy),typeId=policy.id||pdmscMasterResolveId_('LEAVE_TYPE',x.leaveType,true),anchorKey=x.effectiveOccurrenceDateKey||pdmscLeaveDateKey_(x.start),allowedRows=(x.dateRows||[]).filter(r=>r.allowWarning),baseAllowedDays=allowedRows.reduce((sum,r)=>sum+(r.days===null?0:Number(r.days||0)),0),extraAllowedDays=Math.max(0,Number(x.warningMonthDays||0)-baseAllowedDays);allowedRows.forEach(r=>{const request=(flags.countOccurrence&&Number(x.warningRequestCount||0)>0&&r.dateKey===anchorKey)?1:0,days=(flags.countDays&&r.days!==null&&r.days!==undefined)?Number(r.days||0)+(r.dateKey===anchorKey?extraAllowedDays:0):0;leave.push({leaveId:x.leaveId,empId:x.empId,name:p.fullName||x.empId,department:p.department||'',departmentId:dep.id||'',dateKey:r.dateKey,leaveType:x.leaveType,leaveTypeId:typeId||'',requests:request,days,needsReview:!!x.effectiveAllocationNeedsReview||r.days===null,sourceNote:x.sourceNote||'',periodOwnership:x.periodOwnership||'IN_PERIOD',effectiveOccurrenceDateKey:anchorKey});});}));
  return{people,pmap,events,leave,activeEvents,effectiveLeaveByMonth:effectiveByMonth,serverMs:Date.now()-started};
}
function pdmscWarningRuleEventMatch_(rule,item){const category=pdmscNormalizeText_(rule.category).toUpperCase();if(category==='LEAVE'){const ids=String(rule.includedTypeIds||'').split('|').map(pdmscNormalizeText_).filter(Boolean);if(ids.length)return !!item.leaveTypeId&&ids.some(x=>x.toUpperCase()===String(item.leaveTypeId).toUpperCase());const names=String(rule.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean);return !!item.leaveType&&names.some(x=>pdmscMasterNormalize_(x)===pdmscMasterNormalize_(item.leaveType));}const selectors=String(rule.includedEventTypes||'').split('|').map(pdmscNormalizeText_).filter(Boolean);return !!item.eventType&&selectors.some(x=>pdmscA02EventSelectorMatch_(x,item.eventType,item.evidence||{}));}
function pdmscWarningBuckets_(rule,selectedMonth,period,settings){const b=pdmscStatisticsMonthBounds_(selectedMonth);if(rule.window==='PERIOD_6M'){const ms=(period.months||[]).map(x=>x.key);if(!ms.length)return[];return[{key:'P6M-'+ms[0]+'-'+ms[ms.length-1],start:pdmscStatisticsMonthBounds_(ms[0]).start,end:pdmscStatisticsMonthBounds_(ms[ms.length-1]).end,label:'ทั้งรอบ 6 เดือน'}];}if(rule.window==='WEEKLY'){const seen=new Map(),d=new Date(b.start);while(d<=b.end){const r=pdmscWarningWeekRangeForDate_(d,settings.WARNING_WEEK_START||'จันทร์',settings.WARNING_WEEK_END||'ศุกร์');if(!seen.has(r.key))seen.set(r.key,{key:r.key,start:r.start,end:r.end,label:pdmscWarningRangeLabel_(r.start,r.end)});d.setDate(d.getDate()+1);}return[...seen.values()];}return[{key:'M-'+selectedMonth,start:b.start,end:b.end,label:pdmscWebMonthLabel_(selectedMonth)}];}
function pdmscWarningMetricValues_(rule,z){const e=rule.evaluationMode||'COUNT',metric=rule.metric||'COUNT',count=Number(z.count||0),total=metric==='DAYS'?Number(z.days||0):metric==='MINUTES'?Number(z.minutes||0):count,primary=Number(rule.threshold||0),secondary=Number(rule.secondaryThreshold||0);let qualified=false,metricBlocked=false;if(e==='COUNT')qualified=count>=primary;else if(e==='TOTAL'){metricBlocked=metric==='DAYS'&&z.unresolvedDays>0;qualified=!metricBlocked&&total>=primary;}else if(e==='COUNT_OR_TOTAL'){const byCount=count>=primary,needTotal=!byCount,blockedTotal=metric==='DAYS'&&z.unresolvedDays>0;metricBlocked=needTotal&&blockedTotal;qualified=byCount||(!blockedTotal&&total>=secondary);}return{count,total,metric,qualified,metricBlocked,primary,secondary};}
function pdmscWarningMetricLabel_(rule,m){if((rule.evaluationMode||'COUNT')==='COUNT')return m.count+' ครั้ง / เกณฑ์ '+m.primary+' ครั้ง';const unit=m.metric==='DAYS'?'วัน':'นาที';if(rule.evaluationMode==='TOTAL')return m.total+' '+unit+' / เกณฑ์ '+m.primary+' '+unit;return m.count+' ครั้ง หรือ '+m.total+' '+unit+' / เกณฑ์ '+m.primary+' ครั้ง หรือ '+m.secondary+' '+unit;}
function pdmscWarningCandidateDataset_(monthKey,force){
  monthKey=pdmscNormalizeMonthKey_(monthKey);const ck='warning-candidates-v020-'+monthKey;if(!force&&typeof pdmscWebCacheGet_==='function'){const c=pdmscWebCacheGet_(ck);if(c)return c;}const started=Date.now(),settings=pdmscSettingsMap_(),rules=pdmscWarningRules_().filter(x=>x.active),period=pdmscWebPeriodView_(),months=pdmscWarningNeededMonths_(monthKey,rules,period),src=pdmscWarningSourceBundle_(months),excludedIds=pdmscWarningExcludedDepartmentIds_(),rows=[];
  rules.forEach(rule=>{const category=pdmscNormalizeText_(rule.category).toUpperCase(),buckets=pdmscWarningBuckets_(rule,monthKey,period,settings),items=category==='LEAVE'?src.leave:src.events;buckets.forEach(bucket=>{const grouped=new Map();items.forEach(it=>{if(!pdmscWarningRuleEventMatch_(rule,it))return;const d=pdmscWarningDateFromKey_(it.dateKey);if(d<bucket.start||d>bucket.end||!pdmscWarningItemWithinRuleRange_(rule,d))return;const key=it.empId,z=grouped.get(key)||{empId:it.empId,name:it.name,department:it.department,departmentId:it.departmentId||'',count:0,days:0,minutes:0,unresolvedDays:0,details:[]};if(category==='LEAVE'){z.count+=Number(it.requests||0);z.days+=Number(it.days||0);if(it.needsReview)z.unresolvedDays++;z.details.push({dateKey:it.dateKey,date:pdmscStatisticsDateUi_(it.dateKey),type:it.leaveType,note:it.sourceNote||'',count:Number(it.requests||0),days:Number(it.days||0),minutes:0});}else{const f=it.facets||pdmscA02EventFacets_(it.eventType,it.evidence||{});z.count+=1;z.minutes+=category==='LATE'?Number(f.lateMinutes||0):0;z.details.push({dateKey:it.dateKey,date:pdmscStatisticsDateUi_(it.dateKey),type:it.eventType,note:((it.evidence||{}).classification||{}).reason||'',count:1,days:0,minutes:category==='LATE'?Number(f.lateMinutes||0):0});}grouped.set(key,z);});grouped.forEach(z=>{const metric=pdmscWarningMetricValues_(rule,z),groupBlocked=!!z.departmentId&&excludedIds.has(z.departmentId),systemEnabled=String(settings.WARNING_ENABLED||'FALSE').toUpperCase()==='TRUE',eligible=metric.qualified&&!metric.metricBlocked&&!groupBlocked&&systemEnabled,reason=metric.metricBlocked?'จำนวนวันลาบางรายการจัดสรรไม่ชัดเจน ต้องตรวจข้อมูลลาก่อน':!metric.qualified?'ยังไม่ถึงเกณฑ์: '+pdmscWarningMetricLabel_(rule,metric):groupBlocked?'กลุ่มนี้ตั้งค่า “เก็บสถิติแต่ไม่ออกหนังสือ”':!systemEnabled?'ระบบการเตือนยังปิดอยู่':'เข้าเกณฑ์และอนุญาตการเตือน';rows.push({candidateKey:[z.empId,rule.ruleId,bucket.key].join('|'),empId:z.empId,name:z.name,department:z.department,departmentId:z.departmentId,ruleId:rule.ruleId,ruleName:rule.name,category:rule.category,window:rule.window,windowKey:bucket.key,windowLabel:bucket.label,count:metric.count,days:z.days,minutes:z.minutes,total:metric.total,metric:metric.metric,evaluationMode:rule.evaluationMode,threshold:metric.primary,secondaryThreshold:metric.secondary,metricLabel:pdmscWarningMetricLabel_(rule,metric),qualified:metric.qualified,metricBlocked:metric.metricBlocked,groupBlocked,systemEnabled,eligible,reason,details:z.details.sort((a,b)=>a.dateKey.localeCompare(b.dateKey))});});});});
  rows.sort((a,b)=>Number(b.eligible)-Number(a.eligible)||Number(b.qualified)-Number(a.qualified)||b.count-a.count||a.name.localeCompare(b.name,'th'));const out=pdmscWebSafe_({ok:true,version:PDMSC_WARNING_CANDIDATE.VERSION,webBuild:PDMSC.WEB_BUILD,monthKey,label:pdmscWebMonthLabel_(monthKey),settings:{enabled:String(settings.WARNING_ENABLED||'FALSE').toUpperCase()==='TRUE',excludedDepartmentIds:[...excludedIds],excludedGroups:pdmscWarningExcludedDepartmentNames_()},rules,sourceMonths:months,summary:{rows:rows.length,qualified:rows.filter(x=>x.qualified).length,eligible:rows.filter(x=>x.eligible).length,blockedGroup:rows.filter(x=>x.groupBlocked&&x.qualified).length,blockedMetric:rows.filter(x=>x.metricBlocked).length,systemDisabled:rows.filter(x=>x.qualified&&!x.systemEnabled).length},rows,sourceReadMs:src.serverMs,serverMs:Date.now()-started});if(typeof pdmscWebCachePut_==='function')pdmscWebCachePut_(ck,out,PDMSC_WARNING_CANDIDATE.CACHE_SECONDS);return out;
}

function pdmscWarningDocumentReason_(candidate){
  const c=pdmscNormalizeText_((candidate||{}).category).toUpperCase();
  if(c==='LATE')return'มาสาย';
  if(c==='MISSING_SCAN')return'ไม่สแกนเวลา';
  if(c==='LEAVE')return'การลา';
  return'การแจ้งเตือน';
}
function pdmscWarningDocumentBoundary_(candidate){
  const x=candidate||{},ready=!!x.eligible&&!x.metricBlocked&&!x.groupBlocked&&!!x.systemEnabled;
  const payload={candidateKey:x.candidateKey||'',empId:x.empId||'',ruleId:x.ruleId||'',windowKey:x.windowKey||'',category:x.category||'',count:Number(x.count||0),days:Number(x.days||0),minutes:Number(x.minutes||0),metric:x.metric||'COUNT',evaluationMode:x.evaluationMode||'COUNT',threshold:Number(x.threshold||0),secondaryThreshold:Number(x.secondaryThreshold||0),qualified:!!x.qualified,eligible:!!x.eligible,documentReason:pdmscWarningDocumentReason_(x)};
  return{ready,reason:ready?'READY_FOR_DOCUMENT_PREVIEW':(x.reason||'NOT_ELIGIBLE'),documentReason:payload.documentReason,candidateKey:payload.candidateKey,empId:payload.empId,ruleId:payload.ruleId,windowKey:payload.windowKey,sourceFingerprint:pdmscAttendanceHash_(JSON.stringify(payload))};
}

function pdmscWarningCandidateBootstrap_(){const period=pdmscWebPeriodView_(),months=period.months||[];return pdmscWebSafe_({ok:true,version:PDMSC_WARNING_CANDIDATE.VERSION,webBuild:PDMSC.WEB_BUILD,period,defaultMonth:months.length?months[0].key:'',loaded:false,warningEnabled:String(pdmscSettingsGet_('WARNING_ENABLED','FALSE')).toUpperCase()==='TRUE',rules:pdmscWarningRules_().filter(x=>x.active).length});}
function pdmscWarningCandidateSelfTest_(){
  const p1=pdmscDecisionPolicy(PDMSC.DECISION.NORMAL),p2=pdmscDecisionPolicy(PDMSC.DECISION.EXCLUDED),p3=pdmscDecisionPolicy(PDMSC.DECISION.EXCLUDED_KEEP_STATS),r=pdmscWarningWeekRangeForDate_(new Date(2026,3,8),'จันทร์','ศุกร์'),countRule={evaluationMode:'COUNT',metric:'COUNT',threshold:2,secondaryThreshold:0},dayRule={evaluationMode:'TOTAL',metric:'DAYS',threshold:2,secondaryThreshold:0},orRule={evaluationMode:'COUNT_OR_TOTAL',metric:'MINUTES',threshold:3,secondaryThreshold:60},dateRule={effectiveStart:new Date(2026,3,1,0),effectiveEnd:new Date(2026,3,3,0)},ready=pdmscWarningDocumentBoundary_({candidateKey:'E|R|M',empId:'E',ruleId:'R',windowKey:'M',category:'LATE',count:3,metric:'COUNT',evaluationMode:'COUNT',threshold:3,qualified:true,eligible:true,systemEnabled:true,groupBlocked:false,metricBlocked:false}),blocked=pdmscWarningDocumentBoundary_({candidateKey:'E|R|M',empId:'E',ruleId:'R',windowKey:'M',qualified:true,eligible:false,systemEnabled:true,groupBlocked:true,metricBlocked:false,reason:'BLOCKED'});
  const tests=[
    {name:'NORMAL may reach Warning',ok:p1.allowWarning===true},
    {name:'EXCLUDED never reaches Warning',ok:p2.allowWarning===false},
    {name:'EXCLUDED_KEEP_STATS preserves statistics but blocks Warning',ok:p3.countStatistics===true&&p3.allowWarning===false},
    {name:'Leave Warning source is effective Leave Core only',ok:typeof pdmscLeaveCoreEffectiveFactsForMonths_==='function'&&typeof pdmscLeaveCoreWarningBaseFromEffectiveFacts_==='function'},
    {name:'Weekly range honors configured weekday span',ok:r.start.getDay()===1&&r.end.getDay()===5},
    {name:'Half-leave late facet reaches late selector',ok:pdmscA02EventSelectorMatch_('LATE','HALF_LEAVE_PM_LATE',{scan:{lateMinutes:5}})},
    {name:'Count metric works',ok:pdmscWarningMetricValues_(countRule,{count:2}).qualified},
    {name:'Day-only metric works without occurrence count',ok:pdmscWarningMetricValues_(dayRule,{count:0,days:2,unresolvedDays:0}).qualified},
    {name:'Late-and-missing-out document reason normalizes to late',ok:pdmscWarningDocumentReason_({category:'LATE',details:[{type:'LATE_AND_MISSING_OUT'}]})==='มาสาย'},
    {name:'Count-or-minutes supports one rule instead of overlap',ok:pdmscWarningMetricValues_(orRule,{count:1,minutes:65}).qualified},
    {name:'Unresolved leave days block day-only warning',ok:pdmscWarningMetricValues_(dayRule,{count:0,days:0,unresolvedDays:1}).metricBlocked},
    {name:'Official duty is not a Leave warning source',ok:pdmscA02EventFacets_('OFFICIAL_DUTY',{}).officialDuty===true},
    {name:'Effective-end day is included even when candidate is noon',ok:pdmscWarningItemWithinRuleRange_(dateRule,new Date(2026,3,3,12))},
    {name:'Day after effective-end is excluded',ok:!pdmscWarningItemWithinRuleRange_(dateRule,new Date(2026,3,4,0))},
    {name:'Document boundary accepts only eligible candidate',ok:ready.ready&&!!ready.sourceFingerprint&&!blocked.ready}
  ];return{ok:tests.every(x=>x.ok),tests};
}
