const PDMSC_DOC_D01=Object.freeze({VERSION:'D01-V0.1.0',A4_WIDTH_PT:595.28,A4_HEIGHT_PT:841.89,LINE_SPACING_MIN:0.70,LINE_SPACING_MAX:2.00});
const PDMSC_DOC_TEMPLATES=Object.freeze({
  MONTHLY_COVER:{setting:'DOC_TEMPLATE_MONTHLY_COVER',label:'หนังสือนำสรุปรายเดือน',required:['DOCUMENT_DATE','REPORT_MONTH_NAME','REPORT_MONTH_START','REPORT_MONTH_END']},
  WARNING_LEAVE_COVER:{setting:'DOC_TEMPLATE_WARNING_LEAVE_COVER',label:'หนังสือนำแจ้งเตือนการลา',required:['DOCUMENT_DATE','WEEK_START_DATE','WEEK_END_DATE','PERSON_COUNT','WARNING_PERSON_LIST']},
  WARNING_LATE_COVER:{setting:'DOC_TEMPLATE_WARNING_LATE_COVER',label:'หนังสือนำแจ้งเตือนการสาย',required:['DOCUMENT_DATE','WEEK_START_DATE','WEEK_END_DATE','PERSON_COUNT','WARNING_PERSON_LIST']},
  WARNING_LEAVE_PERSON:{setting:'DOC_TEMPLATE_WARNING_LEAVE_PERSON',label:'หนังสือเตือนรายบุคคลการลา',required:['DOCUMENT_DATE','FULL_NAME','POSITION','WEEK_START_DATE','WEEK_END_DATE','WEEK_STAT_TEXT','MONTH_TO_DATE_STAT_TEXT','BUDGET_CUMULATIVE_STAT_TEXT']},
  WARNING_LATE_PERSON:{setting:'DOC_TEMPLATE_WARNING_LATE_PERSON',label:'หนังสือเตือนรายบุคคลการสาย',required:['DOCUMENT_DATE','FULL_NAME','POSITION','WEEK_START_DATE','WEEK_END_DATE','WEEK_STAT_TEXT','MONTH_TO_DATE_STAT_TEXT','BUDGET_CUMULATIVE_STAT_TEXT']},
  WARNING_LEAVE_ATTACHMENT:{setting:'DOC_TEMPLATE_WARNING_LEAVE_ATTACHMENT',label:'เอกสารแนบข้อมูลสถิติรายบุคคลการลา',required:['FULL_NAME','POSITION','DEPARTMENT','WEEK_START_DATE','WEEK_END_DATE','EVENT_DETAIL_TABLE']},
  WARNING_LATE_ATTACHMENT:{setting:'DOC_TEMPLATE_WARNING_LATE_ATTACHMENT',label:'เอกสารแนบข้อมูลสถิติรายบุคคลการสาย',required:['FULL_NAME','POSITION','DEPARTMENT','WEEK_START_DATE','WEEK_END_DATE','EVENT_DETAIL_TABLE']}
});
function pdmscDocExtractFileId_(v){const s=String(v||'').trim();if(!s)return'';const m=s.match(/\/d\/([a-zA-Z0-9_-]+)/)||s.match(/\/folders\/([a-zA-Z0-9_-]+)/)||s.match(/id=([a-zA-Z0-9_-]+)/);return m?m[1]:s.replace(/\\_/g,'_');}
function pdmscDocStyleProfile_(){const m=pdmscSettingsMap_(),n=(k,d)=>{const x=Number(m[k]);return Number.isFinite(x)?x:d},ls=n('DOC_STYLE_LINE_SPACING',0.9);return{profileName:m.DOC_STYLE_PROFILE_NAME||'ค่าเริ่มต้น',fontFamily:m.DOC_STYLE_FONT_FAMILY||'TH SarabunPSK',fontSize:Math.max(8,Math.min(40,n('DOC_STYLE_FONT_SIZE',16))),lineSpacing:Math.max(PDMSC_DOC_D01.LINE_SPACING_MIN,Math.min(PDMSC_DOC_D01.LINE_SPACING_MAX,ls)),tabPoints:Math.max(18,Math.min(90,n('DOC_STYLE_TAB_POINTS',36))),revision:String(m.DOC_STYLE_REVISION||'1')};}
function pdmscDocTemplateRegistry_(){const m=pdmscSettingsMap_();return Object.keys(PDMSC_DOC_TEMPLATES).map(code=>{const spec=PDMSC_DOC_TEMPLATES[code],raw=m[spec.setting]||'',id=pdmscDocExtractFileId_(raw);return{code,label:spec.label,setting:spec.setting,value:raw,fileId:id,required:spec.required.slice()};});}
function pdmscDocSettingsPayload_(){const m=pdmscSettingsMap_();return pdmscWebSafe_({settings:{SCHOOL_NAME:m.SCHOOL_NAME||'',DIRECTOR_NAME:m.DIRECTOR_NAME||'',HR_DEPUTY_NAME:m.HR_DEPUTY_NAME||'',ASSISTANT_DIRECTOR_NAME:m.ASSISTANT_DIRECTOR_NAME||'',DOC_OUTPUT_FOLDER_ID:m.DOC_OUTPUT_FOLDER_ID||''},templates:pdmscDocTemplateRegistry_(),style:pdmscDocStyleProfile_(),a4:{widthPt:PDMSC_DOC_D01.A4_WIDTH_PT,heightPt:PDMSC_DOC_D01.A4_HEIGHT_PT}});}
function pdmscDocSaveSettings_(payload){payload=payload||{};const allowed=['DOC_OUTPUT_FOLDER_ID','DOC_STYLE_PROFILE_NAME','DOC_STYLE_FONT_FAMILY','DOC_STYLE_FONT_SIZE','DOC_STYLE_LINE_SPACING','DOC_STYLE_TAB_POINTS','DOC_STYLE_REVISION'];Object.keys(PDMSC_DOC_TEMPLATES).forEach(code=>allowed.push(PDMSC_DOC_TEMPLATES[code].setting));const out={};allowed.forEach(k=>{if(!(k in payload))return;let v=String(payload[k]==null?'':payload[k]).trim();if(k.indexOf('DOC_TEMPLATE_')===0)v=pdmscDocExtractFileId_(v);if(k==='DOC_STYLE_LINE_SPACING'){const n=Number(v);if(!Number.isFinite(n)||n<PDMSC_DOC_D01.LINE_SPACING_MIN||n>PDMSC_DOC_D01.LINE_SPACING_MAX)throw new Error('ระยะห่างบรรทัดต้องอยู่ระหว่าง 0.70–2.00');v=n.toFixed(2);}if(k==='DOC_STYLE_FONT_SIZE'){const n=Number(v);if(!Number.isFinite(n)||n<8||n>40)throw new Error('ขนาดอักษรต้องอยู่ระหว่าง 8–40 pt');v=String(n);}if(k==='DOC_STYLE_TAB_POINTS'){const n=Number(v);if(!Number.isFinite(n)||n<18||n>90)throw new Error('ระยะ 1 Tab ต้องอยู่ระหว่าง 18–90 pt');v=String(n);}pdmscSettingsUpsert_(k,v,'D01 document settings');out[k]=v;});pdmscWebCacheClear_(['settings-tab-document','documents-history']);return pdmscDocSettingsPayload_();}
function pdmscDocReadAllText_(doc){return[doc.getBody(),doc.getHeader(),doc.getFooter()].filter(Boolean).map(x=>String(x.getText?x.getText():'')).join('\n');}
function pdmscDocValidateTemplate_(code){const spec=PDMSC_DOC_TEMPLATES[code];if(!spec)throw new Error('ไม่รู้จักแม่แบบ '+code);const item=pdmscDocTemplateRegistry_().find(x=>x.code===code),out={code,label:spec.label,fileId:item?item.fileId:'',ok:false,missing:[],note:''};if(!out.fileId){out.note='ยังไม่ได้ตั้ง File ID';return out;}try{const f=DriveApp.getFileById(out.fileId);if(f.getMimeType()!==MimeType.GOOGLE_DOCS){out.note='ไฟล์ไม่ใช่ Google Docs';return out;}const doc=DocumentApp.openById(out.fileId),text=pdmscDocReadAllText_(doc);out.missing=spec.required.filter(k=>text.indexOf('{{'+k+'}}')<0);out.ok=out.missing.length===0;out.note=out.ok?'พร้อมใช้':'Placeholder ไม่ครบ: '+out.missing.join(', ');return out;}catch(e){out.note='เปิดแม่แบบไม่ได้: '+String(e&&e.message||e);return out;}}
function pdmscDocValidateAllTemplates_(){const items=Object.keys(PDMSC_DOC_TEMPLATES).map(pdmscDocValidateTemplate_);return{ok:items.every(x=>x.ok),items};}
function pdmscDocApplyA4_(doc){const b=doc.getBody();if(typeof b.setPageWidth==='function')b.setPageWidth(PDMSC_DOC_D01.A4_WIDTH_PT);if(typeof b.setPageHeight==='function')b.setPageHeight(PDMSC_DOC_D01.A4_HEIGHT_PT);return true;}
function pdmscDocApplyParagraphStyle_(p,level,profile){profile=profile||pdmscDocStyleProfile_();const indent=profile.tabPoints*(level===2?2:1);if(typeof p.setIndentStart==='function')p.setIndentStart(indent);if(typeof p.setIndentFirstLine==='function')p.setIndentFirstLine(indent);if(typeof p.setIndentEnd==='function')p.setIndentEnd(0);if(typeof p.setSpacingBefore==='function')p.setSpacingBefore(0);if(typeof p.setSpacingAfter==='function')p.setSpacingAfter(0);if(typeof p.setLineSpacing==='function')p.setLineSpacing(profile.lineSpacing);if(typeof p.setAlignment==='function')p.setAlignment(DocumentApp.HorizontalAlignment.LEFT);const t=p.editAsText();if(t&&String(t.getText()||'').length){if(profile.fontFamily&&typeof t.setFontFamily==='function')t.setFontFamily(profile.fontFamily);if(typeof t.setFontSize==='function')t.setFontSize(profile.fontSize);if(typeof t.setBold==='function')t.setBold(false);}return p;}
function pdmscDocReplaceWarningPersonList_(doc,lines){if(!Array.isArray(lines)||!lines.length||lines.length%2)throw new Error('รายชื่อหนังสือนำต้องมี 2 บรรทัดต่อบุคลากร');const body=doc.getBody(),targets=[];for(let i=0;i<body.getNumChildren();i++){const c=body.getChild(i);if(c.getType()===DocumentApp.ElementType.PARAGRAPH&&String(c.getText()||'').trim()==='{{WARNING_PERSON_LIST}}')targets.push(c);}if(targets.length!==1)throw new Error('แม่แบบหนังสือนำต้องมี {{WARNING_PERSON_LIST}} เดี่ยว exactly 1 จุด');const target=targets[0],parent=target.getParent(),idx=parent.getChildIndex(target),profile=pdmscDocStyleProfile_();lines.forEach((line,i)=>pdmscDocApplyParagraphStyle_(parent.insertParagraph(idx+i,String(line||'')),i%2===0?1:2,profile));parent.removeChild(target);return{paragraphs:lines.length,style:profile};}
function pdmscDocKeepSignatureTableTogether_(doc){const body=doc.getBody(),tables=[];for(let i=0;i<body.getNumChildren();i++){const c=body.getChild(i);if(c.getType()===DocumentApp.ElementType.TABLE)tables.push(c);}if(tables.length<2)return{ok:false,note:'ไม่พบตารางลายเซ็นผู้บริหาร'};const table=tables[tables.length-1],paras=[];for(let r=0;r<table.getNumRows();r++){const row=table.getRow(r);for(let c=0;c<row.getNumCells();c++){const cell=row.getCell(c);for(let i=0;i<cell.getNumChildren();i++){const el=cell.getChild(i);if(el.getType()===DocumentApp.ElementType.PARAGRAPH||el.getType()===DocumentApp.ElementType.LIST_ITEM)paras.push(el);}}}paras.forEach((p,i)=>{if(typeof p.setKeepWithNext==='function')p.setKeepWithNext(i<paras.length-1);});const tableIndex=body.getChildIndex(table);if(tableIndex>0){const prev=body.getChild(tableIndex-1);if((prev.getType()===DocumentApp.ElementType.PARAGRAPH||prev.getType()===DocumentApp.ElementType.LIST_ITEM)&&typeof prev.setKeepWithNext==='function')prev.setKeepWithNext(false);}return{ok:true,paragraphs:paras.length,note:'ใช้ Keep with next ภายในตาราง เพื่อให้ย้ายทั้งกลุ่มเมื่อพื้นที่ไม่พอ โดยไม่บังคับขึ้นหน้าใหม่ถ้ายังมีพื้นที่'};}
function pdmscDocTemplateSelfTest_(){const s=pdmscDocStyleProfile_(),tests=[{name:'Line spacing supports 0.8/0.9',ok:s.lineSpacing>=0.7&&s.lineSpacing<=2},{name:'A4 contract fixed',ok:Math.abs(PDMSC_DOC_D01.A4_WIDTH_PT-595.28)<0.1&&Math.abs(PDMSC_DOC_D01.A4_HEIGHT_PT-841.89)<0.1},{name:'Seven Thai production template roles',ok:Object.keys(PDMSC_DOC_TEMPLATES).length===7},{name:'Two-line indentation uses one/two tab widths',ok:s.tabPoints>0}];return{ok:tests.every(x=>x.ok),tests};}
